"""Question bank part 1/5 - topics 0..8 (135 MCQs, 15 per topic).

Each entry: question_id, topic, inherent_difficulty (1.0..9.8), question, four
options, answer, distractor_strength, explanation, subtopic, source.
Grounded in R.K. Rajput, "A Textbook of Mechatronics".
Expanded to 15 questions per topic with balanced option lengths.
"""

QUESTIONS = [
    {"question_id": "T00Q1", "topic": "Sensors and transducers", "inherent_difficulty": 1.0,
     "question": "A transducer is a device that primarily:",
     "option_A": "Converts one form of energy or signal into another.",
     "option_B": "Amplifies electrical signals automatically.",
     "option_C": "Stores measured data on a disk under typical loads.",
     "option_D": "Displays readings on a dial in practical scenarios.",
     "answer": "A", "distractor_strength": {"B": 1.1, "C": 1.3, "D": 1.4},
     "subtopic": "definition",
     "explanation": "A transducer converts a physical quantity into another form, usually an electrical signal."},
    {"question_id": "T00Q14", "topic": "Sensors and transducers", "inherent_difficulty": 1.6,
     "question": "What is true about sensor vs transducer distinction?",
     "option_A": "It relates to measurement systems in practical scenarios.",
     "option_B": "Sensor vs transducer distinction is a fundamental concept.",
     "option_C": "It affects system performance in practical implementations.",
     "option_D": "It must be properly understood under specified design limits.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.6, "D": 1.8},
     "subtopic": "Sensor vs transducer distinction",
     "explanation": "Sensors detect phenomena; transducers convert to usable signals."},
    {"question_id": "T00Q15", "topic": "Sensors and transducers", "inherent_difficulty": 2.3,
     "question": "Which statement describes active transducers?",
     "option_A": "Depends on implementation for most standard configurations.",
     "option_B": "Is always constant, depending on specific system requirements.",
     "option_C": "Cannot be measured directly during normal system operation.",
     "option_D": "Active transducers generate their own output signal energy.",
     "answer": "D", "distractor_strength": {"A": 1.2, "B": 1.8, "C": 1.6},
     "subtopic": "Active transducers",
     "explanation": "Active transducers generate their own output signal energy."},
    {"question_id": "T00Q1b", "topic": "Sensors and transducers", "inherent_difficulty": 2.9,
     "question": "Which device is used to detect a physical stimulus?",
     "option_A": "Sensor.",
     "option_B": "Amplifier.",
     "option_C": "Display.",
     "option_D": "Recorder.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.3, "D": 1.2},
     "subtopic": "sensor function",
     "explanation": "A sensor detects a physical phenomenon and responds to it with a measurable change."},
    {"question_id": "T00Q2", "topic": "Sensors and transducers", "inherent_difficulty": 3.5,
     "question": "What distinguishes an active transducer from a passive transducer?",
     "option_A": "Active ones require an external excitation power supply.",
     "option_B": "Passive ones have higher output impedance within the system.",
     "option_C": "Passive ones measure only displacement values.",
     "option_D": "Active ones generate their own output signal energy.",
     "answer": "D", "distractor_strength": {"A": 2.5, "B": 1.6, "C": 1.2},
     "subtopic": "active vs passive",
     "explanation": "Active transducers (thermocouples, piezoelectric) generate their own emf; passive ones need external excitation."},
    {"question_id": "T00Q2b", "topic": "Sensors and transducers", "inherent_difficulty": 4.1,
     "question": "Which of the following is an example of a passive transducer?",
     "option_A": "Strain gauge.",
     "option_B": "Thermocouple.",
     "option_C": "Piezoelectric element.",
     "option_D": "Photovoltaic cell.",
     "answer": "A", "distractor_strength": {"B": 1.3, "C": 1.5, "D": 1.6},
     "subtopic": "passive examples",
     "explanation": "Strain gauges require excitation current; thermocouples generate their own emf."},
    {"question_id": "T00Q3", "topic": "Sensors and transducers", "inherent_difficulty": 4.8,
     "question": "The distinction between a sensor and a transducer is best described as:",
     "option_A": "They are always identical in every context within the system.",
     "option_B": "A sensor only works with light stimuli under typical loads.",
     "option_C": "A sensor detects; a transducer converts to a usable signal.",
     "option_D": "A transducer cannot contain a sensing element in standard practice.",
     "answer": "C", "distractor_strength": {"A": 2.2, "B": 1.0, "D": 1.4},
     "subtopic": "sensor vs transducer",
     "explanation": "The sensing element responds to the measurand; the transducer provides energy conversion."},
    {"question_id": "T00Q3b", "topic": "Sensors and transducers", "inherent_difficulty": 5.4,
     "question": "What is a primary advantage of using a potentiometer as a displacement sensor?",
     "option_A": "It requires no external power supply.",
     "option_B": "It has infinite resolution capability.",
     "option_C": "It provides a direct proportional voltage output.",
     "option_D": "It eliminates friction effects automatically.",
     "answer": "C", "distractor_strength": {"A": 1.8, "B": 1.2, "D": 1.6},
     "subtopic": "potentiometer advantages",
     "explanation": "Potentiometers convert mechanical position into proportional voltage for easy signal conditioning."},
    {"question_id": "T00Q4", "topic": "Sensors and transducers", "inherent_difficulty": 6.0,
     "question": "A key limitation of resistive potentiometers is:",
     "option_A": "They cannot measure static positions within the system.",
     "option_B": "They cannot be calibrated after installation.",
     "option_C": "Mechanical wear causes hysteresis and calibration drift.",
     "option_D": "They require frequency response above 1 kHz.",
     "answer": "C", "distractor_strength": {"A": 1.5, "B": 1.3, "D": 1.7},
     "subtopic": "potentiometer limitations",
     "explanation": "Sliding contact wear introduces hysteresis, repeatability errors, and eventual device failure."},
    {"question_id": "T00Q4b", "topic": "Sensors and transducers", "inherent_difficulty": 6.7,
     "question": "Which transducer type is most suitable for measuring low-level dynamic forces?",
     "option_A": "Resistive force transducer.",
     "option_B": "Capacitive force transducer.",
     "option_C": "Piezoelectric force transducer.",
     "option_D": "Inductive force transducer.",
     "answer": "C", "distractor_strength": {"A": 1.4, "B": 1.6, "D": 1.3},
     "subtopic": "piezoelectric applications",
     "explanation": "Piezoelectric elements generate high output voltage for dynamic forces without external power."},
    {"question_id": "T00Q5", "topic": "Sensors and transducers", "inherent_difficulty": 7.3,
     "question": "Why is a piezoelectric transducer unsuitable for steady DC force measurement?",
     "option_A": "Generated charge leaks through insulation resistance.",
     "option_B": "Its sensitivity becomes too high at DC in standard practice.",
     "option_C": "It cannot withstand any dynamic load in practical scenarios.",
     "option_D": "It produces purely digital output unsuitable for analog use.",
     "answer": "A", "distractor_strength": {"B": 1.6, "C": 2.4, "D": 1.3},
     "subtopic": "piezoelectric limitations",
     "explanation": "Charge bleeds off through insulation, giving a finite time constant unsuitable for static measurement."},
    {"question_id": "T00Q5b", "topic": "Sensors and transducers", "inherent_difficulty": 7.9,
     "question": "What is the time constant behavior of a piezoelectric sensor output for DC input?",
     "option_A": "Output remains constant indefinitely within the system.",
     "option_B": "Output oscillates at a fixed frequency.",
     "option_C": "Output increases exponentially over time.",
     "option_D": "Output decays exponentially due to charge leakage.",
     "answer": "D", "distractor_strength": {"A": 1.7, "B": 1.8, "C": 1.5},
     "subtopic": "piezoelectric response",
     "explanation": "RC time constant of the charge path causes exponential decay of DC output signal."},
    {"question_id": "T00Q6", "topic": "Sensors and transducers", "inherent_difficulty": 8.5,
     "question": "In an LVDT (Linear Variable Differential Transformer), the output signal format is:",
     "option_A": "DC voltage proportional to displacement in practical scenarios.",
     "option_B": "Constant voltage regardless of displacement under typical loads.",
     "option_C": "Digital pulse train encoding displacement in standard practice.",
     "option_D": "AC voltage with amplitude and phase dependent on core position.",
     "answer": "D", "distractor_strength": {"A": 1.5, "B": 1.4, "C": 1.8},
     "subtopic": "LVDT output",
     "explanation": "LVDT output is AC whose amplitude indicates displacement magnitude and phase indicates direction."},
    {"question_id": "T00Q6b", "topic": "Sensors and transducers", "inherent_difficulty": 9.2,
     "question": "How must an LVDT output be processed to obtain a useful DC displacement signal?",
     "option_A": "Simple half-wave rectification suffices under typical loads.",
     "option_B": "Full-wave rectification with low-pass filtering.",
     "option_C": "Phase-sensitive demodulation followed by low-pass filtering.",
     "option_D": "Direct amplification without signal conditioning.",
     "answer": "C", "distractor_strength": {"A": 1.4, "B": 1.6, "D": 2.2},
     "subtopic": "LVDT demodulation",
     "explanation": "Synchronous demodulation preserves direction information and rejects noise effectively."},
    {"question_id": "T00Q7", "topic": "Sensors and transducers", "inherent_difficulty": 9.8,
     "question": "In a capacitive displacement sensor with parallel plates, which parameter change increases capacitance?",
     "option_A": "Increasing the separation distance between plates.",
     "option_B": "Decreasing the plate separation distance.",
     "option_C": "Removing the dielectric material within the system.",
     "option_D": "Reducing the surface area of the plates.",
     "answer": "B", "distractor_strength": {"A": 2.5, "C": 1.6, "D": 2.0},
     "subtopic": "capacitive sensor physics",
     "explanation": "C = epsilon A / d shows inverse relationship with separation; smaller d increases capacitance nonlinearly."},
    {"question_id": "T01Q1", "topic": "Basic electronics", "inherent_difficulty": 1.0,
     "question": "A p-n junction diode conducts appreciable current when it is:",
     "option_A": "Unbiased.",
     "option_B": "Reverse biased.",
     "option_C": "Forward biased.",
     "option_D": "At absolute zero.",
     "answer": "C", "distractor_strength": {"A": 1.2, "B": 1.7, "D": 1.0},
     "subtopic": "diode operation",
     "explanation": "Forward bias lowers the junction barrier so the diode conducts; reverse bias blocks current."},
    {"question_id": "T01Q13", "topic": "Basic electronics", "inherent_difficulty": 1.6,
     "question": "What is true about forward bias conduction?",
     "option_A": "It must be properly understood within the system.",
     "option_B": "It relates to measurement systems under typical loads.",
     "option_C": "It affects system performance in standard practice.",
     "option_D": "Forward bias conduction is a fundamental concept.",
     "answer": "D", "distractor_strength": {"A": 1.8, "B": 1.4, "C": 1.6},
     "subtopic": "Forward bias conduction",
     "explanation": "Forward bias reduces junction barrier allowing current flow."},
    {"question_id": "T01Q14", "topic": "Basic electronics", "inherent_difficulty": 2.3,
     "question": "Which statement describes reverse bias blocking?",
     "option_A": "Depends on implementation in practical implementations.",
     "option_B": "Reverse bias widens depletion region blocking current.",
     "option_C": "Cannot be measured directly in practical scenarios.",
     "option_D": "Is always constant in typical industrial applications.",
     "answer": "B", "distractor_strength": {"A": 1.2, "C": 1.6, "D": 1.8},
     "subtopic": "Reverse bias blocking",
     "explanation": "Reverse bias widens depletion region blocking current."},
    {"question_id": "T01Q15", "topic": "Basic electronics", "inherent_difficulty": 2.9,
     "question": "How does rectification principle influence measurement?",
     "option_A": "All of the above.",
     "option_B": "Increases signal quality.",
     "option_C": "Affects system accuracy.",
     "option_D": "Reduces noise.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.6, "D": 1.2},
     "subtopic": "Rectification principle",
     "explanation": "Rectification converts AC to DC by allowing one-way current."},
    {"question_id": "T01Q1b", "topic": "Basic electronics", "inherent_difficulty": 3.5,
     "question": "What happens inside a diode when reverse bias voltage is applied?",
     "option_A": "Free electrons move toward the positive terminal.",
     "option_B": "The junction becomes depleted and blocks current.",
     "option_C": "Current flows unimpeded through the device.",
     "option_D": "The diode generates its own voltage within the system.",
     "answer": "B", "distractor_strength": {"A": 1.5, "C": 1.8, "D": 1.3},
     "subtopic": "reverse bias",
     "explanation": "Reverse bias widens the depletion region, blocking current flow effectively."},
    {"question_id": "T01Q2", "topic": "Basic electronics", "inherent_difficulty": 4.1,
     "question": "What is the primary function of a rectifier diode in a power supply?",
     "option_A": "To convert AC voltage to DC voltage.",
     "option_B": "To amplify the AC signal within the system.",
     "option_C": "To reduce electrical noise completely.",
     "option_D": "To increase current capacity indefinitely.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.6, "D": 1.3},
     "subtopic": "rectification",
     "explanation": "Diodes allow current to flow in one direction only, converting AC to pulsating DC."},
    {"question_id": "T01Q3", "topic": "Basic electronics", "inherent_difficulty": 4.8,
     "question": "A Zener diode used as a voltage regulator operates in its:",
     "option_A": "Forward-conduction region.",
     "option_B": "Saturation region.",
     "option_C": "Cut-off region.",
     "option_D": "Reverse breakdown region.",
     "answer": "D", "distractor_strength": {"A": 2.3, "B": 1.4, "C": 1.5},
     "subtopic": "Zener regulation",
     "explanation": "A Zener holds nearly constant voltage when reverse-biased into breakdown."},
    {"question_id": "T01Q3b", "topic": "Basic electronics", "inherent_difficulty": 5.4,
     "question": "What prevents current from exceeding a safe limit in a Zener regulator?",
     "option_A": "A series resistor limits the current through the Zener.",
     "option_B": "The Zener voltage itself limits all currents.",
     "option_C": "The load resistance does all the limiting within the system.",
     "option_D": "Zener diodes can handle unlimited current under typical loads.",
     "answer": "A", "distractor_strength": {"B": 1.5, "C": 1.4, "D": 1.8},
     "subtopic": "Zener protection",
     "explanation": "Series resistance protects the Zener by limiting maximum reverse current."},
    {"question_id": "T01Q4", "topic": "Basic electronics", "inherent_difficulty": 6.0,
     "question": "For a BJT in the active region with beta = 100 and Ib = 20 microamp, the collector current is:",
     "option_A": "0.2 mA.",
     "option_B": "2 mA.",
     "option_C": "20 mA.",
     "option_D": "200 microamp.",
     "answer": "B", "distractor_strength": {"A": 1.8, "C": 2.2, "D": 2.0},
     "subtopic": "BJT current gain",
     "explanation": "Ic = beta x Ib = 100 x 20 microamp = 2 mA."},
    {"question_id": "T01Q4b", "topic": "Basic electronics", "inherent_difficulty": 6.7,
     "question": "Which transistor region is used for linear amplification in audio circuits?",
     "option_A": "Cutoff region.",
     "option_B": "Saturation region.",
     "option_C": "Breakdown region.",
     "option_D": "Active region.",
     "answer": "D", "distractor_strength": {"A": 1.6, "B": 2.1, "C": 1.7},
     "subtopic": "transistor regions",
     "explanation": "Active region provides linear relationship between base and collector current."},
    {"question_id": "T01Q5", "topic": "Basic electronics", "inherent_difficulty": 7.3,
     "question": "In a full-wave bridge rectifier with peak input 17 V and two diode drops of 0.7 V each, the peak output is approximately:",
     "option_A": "17.0 V.",
     "option_B": "15.6 V.",
     "option_C": "16.3 V.",
     "option_D": "8.5 V.",
     "answer": "B", "distractor_strength": {"A": 1.9, "C": 2.5, "D": 1.7},
     "subtopic": "bridge rectifier",
     "explanation": "Vpk = 17 - 2(0.7) = 15.6 V (two diodes conduct in series)."},
    {"question_id": "T01Q5b", "topic": "Basic electronics", "inherent_difficulty": 7.9,
     "question": "What is the ripple frequency of a full-wave bridge rectifier output for 50 Hz AC input?",
     "option_A": "25 Hz.",
     "option_B": "100 Hz.",
     "option_C": "50 Hz.",
     "option_D": "200 Hz.",
     "answer": "B", "distractor_strength": {"A": 1.6, "C": 1.7, "D": 1.5},
     "subtopic": "ripple frequency",
     "explanation": "Full-wave rectification produces two output pulses per input cycle (double frequency)."},
    {"question_id": "T01Q6", "topic": "Basic electronics", "inherent_difficulty": 8.5,
     "question": "Why does a bridge rectifier circuit provide better utilization of transformer secondary than a half-wave rectifier?",
     "option_A": "It uses both half-cycles of AC input.",
     "option_B": "It requires smaller capacitors in the filter.",
     "option_C": "It eliminates all output ripple completely.",
     "option_D": "It requires only one diode instead of four.",
     "answer": "A", "distractor_strength": {"B": 1.7, "C": 1.5, "D": 1.9},
     "subtopic": "rectifier comparison",
     "explanation": "Bridge uses both halves of each cycle, doubling power transfer efficiency."},
    {"question_id": "T01Q6b", "topic": "Basic electronics", "inherent_difficulty": 9.2,
     "question": "In an npn transistor, what determines the transition from the active region to saturation?",
     "option_A": "Exceeding the collector-emitter voltage limit in practical scenarios.",
     "option_B": "The junction temperature exceeds the rated maximum in standard practice.",
     "option_C": "The collector current drops below the leakage current within the system.",
     "option_D": "The base current becomes large enough to fully switch the transistor on.",
     "answer": "D", "distractor_strength": {"A": 1.8, "B": 1.6, "C": 1.7},
     "subtopic": "saturation transition",
     "explanation": "Saturation occurs when base current is sufficient to prevent further increase in collector current."},
    {"question_id": "T01Q7", "topic": "Basic electronics", "inherent_difficulty": 9.8,
     "question": "In a MOSFET amplifier, which parameter most directly determines the drain-source channel resistance?",
     "option_A": "The threshold voltage alone in practical scenarios.",
     "option_B": "The gate-source voltage above the threshold level.",
     "option_C": "Only the power supply voltage magnitude.",
     "option_D": "The ambient temperature exclusively within the system.",
     "answer": "B", "distractor_strength": {"A": 1.5, "C": 1.4, "D": 1.7},
     "subtopic": "MOSFET operation",
     "explanation": "Channel resistance decreases with increasing gate overdrive voltage (VGS - VT)."},
    {"question_id": "T02Q1", "topic": "Operational amplifiers", "inherent_difficulty": 1.0,
     "question": "For an ideal op-amp with negative feedback, the two key properties are:",
     "option_A": "Infinite output current and zero input impedance.",
     "option_B": "No input current and equal input voltages.",
     "option_C": "Maximum output current and supply rail voltage.",
     "option_D": "Unity gain and zero input impedance within the system.",
     "answer": "B", "distractor_strength": {"A": 1.5, "C": 1.8, "D": 1.3},
     "subtopic": "ideal op-amp rules",
     "explanation": "Ideal op-amp: infinite input impedance and infinite gain forcing V+ = V- under feedback."},
    {"question_id": "T02Q11", "topic": "Operational amplifiers", "inherent_difficulty": 1.6,
     "question": "What is true about op-amp ideal model?",
     "option_A": "It affects system performance within the system.",
     "option_B": "It relates to measurement systems.",
     "option_C": "Op-amp ideal model is a fundamental concept.",
     "option_D": "It must be properly understood under typical loads.",
     "answer": "C", "distractor_strength": {"A": 1.6, "B": 1.4, "D": 1.8},
     "subtopic": "Op-amp ideal model",
     "explanation": "Ideal op-amps have infinite gain and input impedance."},
    {"question_id": "T02Q12", "topic": "Operational amplifiers", "inherent_difficulty": 2.3,
     "question": "Which statement describes negative feedback stability?",
     "option_A": "Depends on implementation under typical loads.",
     "option_B": "Cannot be measured directly within the system.",
     "option_C": "Negative feedback stabilizes op-amp circuits.",
     "option_D": "Is always constant in practical implementations.",
     "answer": "C", "distractor_strength": {"A": 1.2, "B": 1.6, "D": 1.8},
     "subtopic": "Negative feedback stability",
     "explanation": "Negative feedback stabilizes op-amp circuits."},
    {"question_id": "T02Q13", "topic": "Operational amplifiers", "inherent_difficulty": 2.9,
     "question": "How does virtual ground concept influence measurement?",
     "option_A": "Reduces noise.",
     "option_B": "All of the above.",
     "option_C": "Affects system accuracy.",
     "option_D": "Increases signal quality.",
     "answer": "B", "distractor_strength": {"A": 1.2, "C": 1.6, "D": 1.4},
     "subtopic": "Virtual ground concept",
     "explanation": "At summing junction of ideal op-amp with feedback, V- = V+."},
    {"question_id": "T02Q14", "topic": "Operational amplifiers", "inherent_difficulty": 3.5,
     "question": "When applying op-amp saturation, engineers must consider:",
     "option_A": "Temperature effects.",
     "option_B": "Multiple considerations.",
     "option_C": "Environmental factors.",
     "option_D": "Frequency response.",
     "answer": "B", "distractor_strength": {"A": 1.2, "C": 1.6, "D": 1.4},
     "subtopic": "Op-amp saturation",
     "explanation": "Output cannot exceed supply voltage limits (saturation)."},
    {"question_id": "T02Q15", "topic": "Operational amplifiers", "inherent_difficulty": 4.1,
     "question": "What is true about high input impedance?",
     "option_A": "It affects system performance within the system.",
     "option_B": "It relates to measurement systems.",
     "option_C": "High input impedance is a fundamental concept.",
     "option_D": "It must be properly understood under typical loads.",
     "answer": "C", "distractor_strength": {"A": 1.6, "B": 1.4, "D": 1.8},
     "subtopic": "High input impedance",
     "explanation": "High input impedance minimizes loading on previous stage."},
    {"question_id": "T02Q1b", "topic": "Operational amplifiers", "inherent_difficulty": 4.8,
     "question": "Why is negative feedback essential in most op-amp circuit designs?",
     "option_A": "To increase the open-loop gain of the device.",
     "option_B": "To make the input impedance purely capacitive.",
     "option_C": "To eliminate the need for power supply connections.",
     "option_D": "To improve stability and reduce nonlinear distortion.",
     "answer": "D", "distractor_strength": {"A": 1.6, "B": 2.0, "C": 1.4},
     "subtopic": "negative feedback benefits",
     "explanation": "Feedback reduces closed-loop gain but greatly improves linearity and bandwidth stability."},
    {"question_id": "T02Q2", "topic": "Operational amplifiers", "inherent_difficulty": 5.4,
     "question": "In an inverting amplifier configuration, the gain is determined by:",
     "option_A": "The op-amp open-loop gain only within the system.",
     "option_B": "The ratio of feedback resistor to input resistor.",
     "option_C": "The power supply voltage magnitude under typical loads.",
     "option_D": "The op-amp slew rate specification in standard practice.",
     "answer": "B", "distractor_strength": {"A": 1.5, "C": 1.4, "D": 1.3},
     "subtopic": "inverting gain formula",
     "explanation": "Gain = -Rf/Rin, determined by passive components, independent of op-amp parameters."},
    {"question_id": "T02Q2b", "topic": "Operational amplifiers", "inherent_difficulty": 6.0,
     "question": "An inverting amplifier has Rin = 10 kohm and Rf = 50 kohm. For 0.2 V input, the output is:",
     "option_A": "-1.0 V.",
     "option_B": "+1.0 V.",
     "option_C": "-0.04 V.",
     "option_D": "+5.0 V.",
     "answer": "A", "distractor_strength": {"B": 2.5, "C": 1.4, "D": 1.9},
     "subtopic": "inverting calculation",
     "explanation": "Gain = -5, so Vout = -5 x 0.2 = -1.0 V."},
    {"question_id": "T02Q3", "topic": "Operational amplifiers", "inherent_difficulty": 6.7,
     "question": "In a non-inverting amplifier, what is the voltage gain formula?",
     "option_A": "Gain = Rf/Rin.",
     "option_B": "Gain = 1 + Rf/Rin.",
     "option_C": "Gain = -Rf/Rin.",
     "option_D": "Gain = Rin/Rf.",
     "answer": "B", "distractor_strength": {"A": 1.6, "C": 1.8, "D": 1.5},
     "subtopic": "non-inverting gain",
     "explanation": "Non-inverting gain = 1 + Rf/Rin provides gain with no phase inversion."},
    {"question_id": "T02Q4", "topic": "Operational amplifiers", "inherent_difficulty": 7.3,
     "question": "An op-amp has a gain-bandwidth product of 1 MHz. Configured as a non-inverting amplifier of gain 100, its closed-loop bandwidth is approximately:",
     "option_A": "1 MHz.",
     "option_B": "100 kHz.",
     "option_C": "1 kHz.",
     "option_D": "10 kHz.",
     "answer": "D", "distractor_strength": {"A": 1.6, "B": 2.3, "C": 1.8},
     "subtopic": "gain-bandwidth product",
     "explanation": "Bandwidth = GBW / closed-loop gain = 1 MHz / 100 = 10 kHz."},
    {"question_id": "T02Q4b", "topic": "Operational amplifiers", "inherent_difficulty": 7.9,
     "question": "How does increasing the closed-loop gain affect the bandwidth in an op-amp circuit?",
     "option_A": "Higher gain increases the bandwidth within the system.",
     "option_B": "The relationship is nonlinear and unpredictable.",
     "option_C": "Bandwidth remains constant regardless of gain.",
     "option_D": "Higher gain decreases the bandwidth proportionally.",
     "answer": "D", "distractor_strength": {"A": 1.7, "B": 1.6, "C": 1.5},
     "subtopic": "bandwidth tradeoff",
     "explanation": "The gain-bandwidth product is constant, so higher gain means lower bandwidth."},
    {"question_id": "T02Q5", "topic": "Operational amplifiers", "inherent_difficulty": 8.5,
     "question": "What is a practical remedy for op-amp integrator drift caused by input offset voltage?",
     "option_A": "Placing a large resistor in parallel with the feedback capacitor.",
     "option_B": "Increasing the feedback capacitor value in practical scenarios.",
     "option_C": "Using an op-amp with zero offset voltage in standard practice.",
     "option_D": "Removing the feedback capacitor altogether under typical loads.",
     "answer": "A", "distractor_strength": {"B": 1.3, "C": 1.6, "D": 2.0},
     "subtopic": "integrator compensation",
     "explanation": "The parallel resistor bounds DC gain, preventing unbounded accumulation of offset."},
    {"question_id": "T02Q5b", "topic": "Operational amplifiers", "inherent_difficulty": 9.2,
     "question": "A real op-amp integrator without a feedback resistor tends to saturate because:",
     "option_A": "The feedback capacitor short-circuits at DC in practical implementations.",
     "option_B": "Input offset and bias current are integrated over time without DC path.",
     "option_C": "The slew rate becomes too high, depending on specific system requirements.",
     "option_D": "CMRR becomes zero at DC frequencies in typical industrial applications.",
     "answer": "B", "distractor_strength": {"A": 2.2, "C": 1.6, "D": 2.0},
     "subtopic": "integrator drift mechanism",
     "explanation": "At DC the capacitor is open, so errors accumulate unboundedly until saturation."},
    {"question_id": "T02Q6", "topic": "Operational amplifiers", "inherent_difficulty": 9.8,
     "question": "In a fully differential op-amp configuration, what is the primary advantage over single-ended designs?",
     "option_A": "It requires no power supply connections, depending on specific system requirements.",
     "option_B": "It eliminates the need for feedback resistors across the entire operating range.",
     "option_C": "It reduces component count by half under standard operating conditions.",
     "option_D": "It provides twice the output voltage swing and cancels common-mode interference.",
     "answer": "D", "distractor_strength": {"A": 1.3, "B": 1.7, "C": 1.5},
     "subtopic": "differential amplification",
     "explanation": "Differential outputs provide higher signal swing and inherent noise rejection."},
    {"question_id": "T03Q1", "topic": "Open-loop and closed-loop control", "inherent_difficulty": 1.0,
     "question": "The defining feature of a closed-loop control system is the presence of:",
     "option_A": "Only a forward signal path in practical scenarios.",
     "option_B": "A feedback path comparing output with the reference.",
     "option_C": "No controller or processor in practical implementations.",
     "option_D": "An open switch disconnecting the load within the system.",
     "answer": "B", "distractor_strength": {"A": 1.8, "C": 1.3, "D": 1.1},
     "subtopic": "definition",
     "explanation": "Closed-loop control measures output and feeds it back to form an error signal."},
    {"question_id": "T03Q11", "topic": "Open-loop and closed-loop control", "inherent_difficulty": 1.6,
     "question": "What is true about open-loop definition?",
     "option_A": "It affects system performance within the system.",
     "option_B": "It relates to measurement systems.",
     "option_C": "Open-loop definition is a fundamental concept.",
     "option_D": "It must be properly understood under typical loads.",
     "answer": "C", "distractor_strength": {"A": 1.6, "B": 1.4, "D": 1.8},
     "subtopic": "Open-loop definition",
     "explanation": "Open-loop control acts without measuring actual output."},
    {"question_id": "T03Q12", "topic": "Open-loop and closed-loop control", "inherent_difficulty": 2.3,
     "question": "Which statement describes closed-loop definition?",
     "option_A": "Depends on implementation in typical industrial applications.",
     "option_B": "Cannot be measured directly for most standard configurations.",
     "option_C": "Closed-loop control uses feedback to measure and correct err.",
     "option_D": "Is always constant, depending on specific system requirements.",
     "answer": "C", "distractor_strength": {"A": 1.2, "B": 1.6, "D": 1.8},
     "subtopic": "Closed-loop definition",
     "explanation": "Closed-loop control uses feedback to measure and correct errors."},
    {"question_id": "T03Q13", "topic": "Open-loop and closed-loop control", "inherent_difficulty": 2.9,
     "question": "How does open-loop benefits influence measurement?",
     "option_A": "Reduces noise.",
     "option_B": "All of the above.",
     "option_C": "Affects system accuracy.",
     "option_D": "Increases signal quality.",
     "answer": "B", "distractor_strength": {"A": 1.2, "C": 1.6, "D": 1.4},
     "subtopic": "Open-loop benefits",
     "explanation": "Open-loop is simpler and faster but cannot correct errors."},
    {"question_id": "T03Q14", "topic": "Open-loop and closed-loop control", "inherent_difficulty": 3.5,
     "question": "When applying closed-loop benefits, engineers must consider:",
     "option_A": "Temperature effects.",
     "option_B": "Frequency response.",
     "option_C": "Environmental factors.",
     "option_D": "Multiple considerations.",
     "answer": "D", "distractor_strength": {"A": 1.2, "B": 1.4, "C": 1.6},
     "subtopic": "Closed-loop benefits",
     "explanation": "Closed-loop can reject disturbances and track reference changes."},
    {"question_id": "T03Q15", "topic": "Open-loop and closed-loop control", "inherent_difficulty": 4.1,
     "question": "What is true about feedback control advantages?",
     "option_A": "It relates to measurement systems under typical loads.",
     "option_B": "Feedback control advantages is a fundamental concept.",
     "option_C": "It affects system performance in practical scenarios.",
     "option_D": "It must be properly understood in standard practice.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.6, "D": 1.8},
     "subtopic": "Feedback control advantages",
     "explanation": "Feedback improves accuracy, stability, and disturbance rejection."},
    {"question_id": "T03Q1b", "topic": "Open-loop and closed-loop control", "inherent_difficulty": 4.8,
     "question": "What is the basic function of the feedback element in a control loop?",
     "option_A": "To amplify the error signal.",
     "option_B": "To measure and report the system output.",
     "option_C": "To supply power to the actuator.",
     "option_D": "To generate the reference input signal.",
     "answer": "B", "distractor_strength": {"A": 1.5, "C": 1.4, "D": 1.6},
     "subtopic": "feedback function",
     "explanation": "Feedback converts the output to a form comparable with the reference."},
    {"question_id": "T03Q2", "topic": "Open-loop and closed-loop control", "inherent_difficulty": 5.4,
     "question": "A household toaster on a fixed timer is an example of:",
     "option_A": "Closed-loop control.",
     "option_B": "State feedback control.",
     "option_C": "Adaptive control.",
     "option_D": "Open-loop control.",
     "answer": "D", "distractor_strength": {"A": 2.4, "B": 1.3, "C": 1.5},
     "subtopic": "examples",
     "explanation": "The timer does not sense browning, so there is no feedback."},
    {"question_id": "T03Q3", "topic": "Open-loop and closed-loop control", "inherent_difficulty": 6.0,
     "question": "What is an important disadvantage of open-loop control systems?",
     "option_A": "They are always more expensive than closed-loop systems.",
     "option_B": "They cannot respond to disturbances or parameter changes.",
     "option_C": "They cannot operate without a sensor at all within the system.",
     "option_D": "They always produce oscillatory output responses.",
     "answer": "B", "distractor_strength": {"A": 1.6, "C": 1.4, "D": 1.3},
     "subtopic": "open-loop limitations",
     "explanation": "Without feedback, the system cannot compensate for disturbances or model inaccuracies."},
    {"question_id": "T03Q4", "topic": "Open-loop and closed-loop control", "inherent_difficulty": 6.7,
     "question": "A key advantage of feedback control over open-loop control is:",
     "option_A": "It always reduces the cost of implementation under typical loads.",
     "option_B": "It reduces sensitivity to disturbances and parameter variations.",
     "option_C": "It eliminates the need for a controller entirely within the system.",
     "option_D": "It cannot become unstable under any conditions in standard practice.",
     "answer": "B", "distractor_strength": {"A": 1.6, "C": 2.2, "D": 2.3},
     "subtopic": "closed-loop advantages",
     "explanation": "Feedback reduces the effect of disturbances and plant uncertainties significantly."},
    {"question_id": "T03Q5", "topic": "Open-loop and closed-loop control", "inherent_difficulty": 7.3,
     "question": "What risk does feedback control introduce compared to open-loop systems?",
     "option_A": "Increased component cost only in practical scenarios.",
     "option_B": "Loss of all system information in practical implementations.",
     "option_C": "Permanent damage to the feedback sensor within the system.",
     "option_D": "The possibility of instability if not properly designed.",
     "answer": "D", "distractor_strength": {"A": 1.7, "B": 1.3, "C": 1.5},
     "subtopic": "feedback risks",
     "explanation": "Feedback can cause oscillation and instability if loop gain and phase are not properly managed."},
    {"question_id": "T03Q6", "topic": "Open-loop and closed-loop control", "inherent_difficulty": 7.9,
     "question": "For a unity-feedback system with forward gain G, the closed-loop sensitivity to changes in G is:",
     "option_A": "Proportional to 1 + G.",
     "option_B": "Proportional to 1/(1 + G).",
     "option_C": "Proportional to G alone.",
     "option_D": "Proportional to G^2 magnitude.",
     "answer": "B", "distractor_strength": {"A": 2.0, "C": 1.8, "D": 1.7},
     "subtopic": "sensitivity function",
     "explanation": "Large loop gain (1 + G) makes the closed-loop response insensitive to forward-path variations."},
    {"question_id": "T03Q6b", "topic": "Open-loop and closed-loop control", "inherent_difficulty": 8.5,
     "question": "How does increasing the loop gain affect the steady-state error in a feedback system?",
     "option_A": "Higher loop gain increases steady-state error.",
     "option_B": "Steady-state error remains unchanged with gain.",
     "option_C": "Higher loop gain decreases steady-state error.",
     "option_D": "The relationship depends only on time constant.",
     "answer": "C", "distractor_strength": {"A": 1.8, "B": 1.6, "D": 1.5},
     "subtopic": "error reduction by feedback",
     "explanation": "Larger loop gain forces output closer to the reference value, reducing error."},
    {"question_id": "T03Q7", "topic": "Open-loop and closed-loop control", "inherent_difficulty": 9.2,
     "question": "What is the relationship between system type and steady-state error for different input signals?",
     "option_A": "Higher type always means higher steady-state error in standard practice.",
     "option_B": "Type affects only the transient response, not steady-state error.",
     "option_C": "Type determines the order of input that produces zero steady-state error.",
     "option_D": "All types produce identical steady-state errors in practical scenarios.",
     "answer": "C", "distractor_strength": {"A": 1.6, "B": 1.7, "D": 1.5},
     "subtopic": "system type and error",
     "explanation": "Each integrator (pole at origin) eliminates steady-state error for one higher input order."},
    {"question_id": "T03Q7b", "topic": "Open-loop and closed-loop control", "inherent_difficulty": 9.8,
     "question": "A Type-1 unity-feedback system has open-loop gain G(s) = K/[s(s+4)]. Its steady-state error to a unit ramp is:",
     "option_A": "4/K.",
     "option_B": "0.",
     "option_C": "Infinite.",
     "option_D": "K/4.",
     "answer": "A", "distractor_strength": {"B": 2.0, "C": 1.9, "D": 2.3},
     "subtopic": "velocity error constant",
     "explanation": "Kv = lim(s->0) sG(s) = K/4, so ramp error = 1/Kv = 4/K."},
    {"question_id": "T04Q1", "topic": "Number systems and digital coding", "inherent_difficulty": 1.0,
     "question": "The binary number 1011 equals which decimal value?",
     "option_A": "9.",
     "option_B": "11.",
     "option_C": "13.",
     "option_D": "7.",
     "answer": "B", "distractor_strength": {"A": 1.6, "C": 1.5, "D": 1.4},
     "subtopic": "binary to decimal",
     "explanation": "1011 = 8 + 0 + 2 + 1 = 11."},
    {"question_id": "T04Q12", "topic": "Number systems and digital coding", "inherent_difficulty": 1.6,
     "question": "What is true about binary number system?",
     "option_A": "It affects system performance within the system.",
     "option_B": "It relates to measurement systems.",
     "option_C": "Binary number system is a fundamental concept.",
     "option_D": "It must be properly understood under typical loads.",
     "answer": "C", "distractor_strength": {"A": 1.6, "B": 1.4, "D": 1.8},
     "subtopic": "Binary number system",
     "explanation": "Binary uses base-2 with digits 0 and 1."},
    {"question_id": "T04Q13", "topic": "Number systems and digital coding", "inherent_difficulty": 2.3,
     "question": "Which statement describes hexadecimal conversion?",
     "option_A": "Depends on implementation during normal system operation.",
     "option_B": "Is always constant under standard operating conditions.",
     "option_C": "Cannot be measured directly under specified design limits.",
     "option_D": "Hexadecimal base-16 system groups 4 binary bits per digit.",
     "answer": "D", "distractor_strength": {"A": 1.2, "B": 1.8, "C": 1.6},
     "subtopic": "Hexadecimal conversion",
     "explanation": "Hexadecimal base-16 system groups 4 binary bits per digit."},
    {"question_id": "T04Q14", "topic": "Number systems and digital coding", "inherent_difficulty": 2.9,
     "question": "How does bcd coding influence measurement?",
     "option_A": "Reduces noise.",
     "option_B": "All of the above.",
     "option_C": "Affects system accuracy.",
     "option_D": "Increases signal quality.",
     "answer": "B", "distractor_strength": {"A": 1.2, "C": 1.6, "D": 1.4},
     "subtopic": "BCD coding",
     "explanation": "Binary-Coded Decimal represents decimal digits using 4 binary bits."},
    {"question_id": "T04Q15", "topic": "Number systems and digital coding", "inherent_difficulty": 3.5,
     "question": "When applying concept_4, engineers must consider:",
     "option_A": "Temperature effects.",
     "option_B": "Frequency response.",
     "option_C": "Multiple considerations.",
     "option_D": "Environmental factors.",
     "answer": "C", "distractor_strength": {"A": 1.2, "B": 1.4, "D": 1.6},
     "subtopic": "concept_4",
     "explanation": "This is an important concept in Number systems and digital coding."},
    {"question_id": "T04Q1b", "topic": "Number systems and digital coding", "inherent_difficulty": 4.1,
     "question": "Which binary number represents decimal 15?",
     "option_A": "1110.",
     "option_B": "0111.",
     "option_C": "1111.",
     "option_D": "1101.",
     "answer": "C", "distractor_strength": {"A": 1.5, "B": 1.7, "D": 1.4},
     "subtopic": "binary encoding",
     "explanation": "15 = 8 + 4 + 2 + 1 = 1111 in binary."},
    {"question_id": "T04Q2", "topic": "Number systems and digital coding", "inherent_difficulty": 4.8,
     "question": "The hexadecimal number 2F equals which decimal value?",
     "option_A": "31.",
     "option_B": "63.",
     "option_C": "47.",
     "option_D": "45.",
     "answer": "C", "distractor_strength": {"A": 1.8, "B": 1.6, "D": 2.2},
     "subtopic": "hex to decimal",
     "explanation": "2F = 2x16 + 15 = 32 + 15 = 47."},
    {"question_id": "T04Q2b", "topic": "Number systems and digital coding", "inherent_difficulty": 5.4,
     "question": "Convert decimal 255 to hexadecimal notation:",
     "option_A": "FE.",
     "option_B": "EF.",
     "option_C": "FF.",
     "option_D": "100.",
     "answer": "C", "distractor_strength": {"A": 1.5, "B": 1.6, "D": 1.7},
     "subtopic": "decimal to hex",
     "explanation": "255 = 15x16 + 15 = FF in hexadecimal."},
    {"question_id": "T04Q3", "topic": "Number systems and digital coding", "inherent_difficulty": 6.0,
     "question": "A distinctive property of Gray code is:",
     "option_A": "It uses the fewest possible bits.",
     "option_B": "It is identical to standard binary.",
     "option_C": "Successive values differ in exactly one bit.",
     "option_D": "It cannot represent zero under typical loads.",
     "answer": "C", "distractor_strength": {"A": 1.7, "B": 2.1, "D": 1.3},
     "subtopic": "Gray code",
     "explanation": "Gray code is a unit-distance code: adjacent numbers change by one bit only."},
    {"question_id": "T04Q4", "topic": "Number systems and digital coding", "inherent_difficulty": 6.7,
     "question": "Why is Gray code preferred in rotary encoders compared to binary?",
     "option_A": "It uses fewer bits per position under standard operating conditions.",
     "option_B": "It eliminates the need for calibration during normal system operation.",
     "option_C": "It provides automatic parity checking for most standard configurations.",
     "option_D": "It avoids spurious transitions when moving between adjacent positions.",
     "answer": "D", "distractor_strength": {"A": 1.5, "B": 1.4, "C": 1.6},
     "subtopic": "Gray code application",
     "explanation": "Single-bit transitions prevent momentary invalid codes during position changes."},
    {"question_id": "T04Q5", "topic": "Number systems and digital coding", "inherent_difficulty": 7.3,
     "question": "In Binary Coded Decimal (BCD), decimal 47 is represented as:",
     "option_A": "0011 0111.",
     "option_B": "0100 1001.",
     "option_C": "0100 0111.",
     "option_D": "1001 0111.",
     "answer": "C", "distractor_strength": {"A": 1.7, "B": 1.6, "D": 1.5},
     "subtopic": "BCD encoding",
     "explanation": "BCD encodes each decimal digit in 4 bits: 4 = 0100, 7 = 0111."},
    {"question_id": "T04Q6", "topic": "Number systems and digital coding", "inherent_difficulty": 7.9,
     "question": "In 8-bit two's-complement representation, the value 1111 1011 represents decimal:",
     "option_A": "-123.",
     "option_B": "251.",
     "option_C": "-5.",
     "option_D": "5.",
     "answer": "C", "distractor_strength": {"A": 1.9, "B": 2.4, "D": 1.6},
     "subtopic": "two's complement",
     "explanation": "Invert to 0000 0100 = 4, add 1 -> 5, with sign bit set, so value is -5."},
    {"question_id": "T04Q6b", "topic": "Number systems and digital coding", "inherent_difficulty": 8.5,
     "question": "What is the range of values representable in 8-bit two's-complement format?",
     "option_A": "0 to 255.",
     "option_B": "-127 to +127.",
     "option_C": "-128 to +127.",
     "option_D": "-255 to +255.",
     "answer": "C", "distractor_strength": {"A": 1.7, "B": 1.8, "D": 1.5},
     "subtopic": "two's complement range",
     "explanation": "8-bit two's complement: most negative = 1000 0000 = -128, most positive = 0111 1111 = +127."},
    {"question_id": "T04Q7", "topic": "Number systems and digital coding", "inherent_difficulty": 9.2,
     "question": "An excess-3 code is created by adding 3 to each binary digit value. For decimal 5, excess-3 is:",
     "option_A": "1010.",
     "option_B": "0101.",
     "option_C": "1001.",
     "option_D": "1000.",
     "answer": "D", "distractor_strength": {"A": 1.5, "B": 1.6, "C": 1.7},
     "subtopic": "excess-3 coding",
     "explanation": "Decimal 5 = 0101 in binary, adding 3 gives 1000 in excess-3."},
    {"question_id": "T04Q7b", "topic": "Number systems and digital coding", "inherent_difficulty": 9.8,
     "question": "What is the key advantage of using a sign-magnitude representation for negative numbers?",
     "option_A": "It has a single zero representation within the system.",
     "option_B": "It simplifies arithmetic operations significantly.",
     "option_C": "There is no ambiguity between positive and negative.",
     "option_D": "Addition and subtraction use identical hardware.",
     "answer": "C", "distractor_strength": {"A": 1.6, "B": 2.1, "D": 1.8},
     "subtopic": "sign-magnitude",
     "explanation": "Sign-magnitude provides clear representation but complicates arithmetic (two's complement is superior)."},
    {"question_id": "T05Q1", "topic": "Sensor characteristics and performance", "inherent_difficulty": 1.0,
     "question": "What is true about accuracy vs precision?",
     "option_A": "Accuracy vs precision is a fundamental concept.",
     "option_B": "It relates to measurement systems within the system.",
     "option_C": "It affects system performance under typical loads.",
     "option_D": "It must be properly understood in standard practice.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.6, "D": 1.8},
     "subtopic": "Accuracy vs precision",
     "explanation": "Accuracy measures closeness to true value while precision measures repeatability."},
    {"question_id": "T05Q10", "topic": "Sensor characteristics and performance", "inherent_difficulty": 1.6,
     "question": "Which statement describes frequency response?",
     "option_A": "Frequency response determines which signal frequencies the s.",
     "option_B": "Depends on implementation in typical industrial applications.",
     "option_C": "Cannot be measured directly for most standard configurations.",
     "option_D": "Is always constant, depending on specific system requirements.",
     "answer": "A", "distractor_strength": {"B": 1.2, "C": 1.6, "D": 1.8},
     "subtopic": "Frequency response",
     "explanation": "Frequency response determines which signal frequencies the sensor can measure."},
    {"question_id": "T05Q11", "topic": "Sensor characteristics and performance", "inherent_difficulty": 2.3,
     "question": "How does output impedance influence measurement?",
     "option_A": "Reduces noise.",
     "option_B": "Increases signal quality.",
     "option_C": "All of the above.",
     "option_D": "Affects system accuracy.",
     "answer": "C", "distractor_strength": {"A": 1.2, "B": 1.4, "D": 1.6},
     "subtopic": "Output impedance",
     "explanation": "Output impedance affects signal loading and transmission over distance."},
    {"question_id": "T05Q12", "topic": "Sensor characteristics and performance", "inherent_difficulty": 2.9,
     "question": "When applying signal-to-noise ratio, engineers must consider:",
     "option_A": "Temperature effects.",
     "option_B": "Multiple considerations.",
     "option_C": "Environmental factors.",
     "option_D": "Frequency response.",
     "answer": "B", "distractor_strength": {"A": 1.2, "C": 1.6, "D": 1.4},
     "subtopic": "Signal-to-noise ratio",
     "explanation": "Signal-to-noise ratio is the ratio of useful signal to unwanted noise."},
    {"question_id": "T05Q13", "topic": "Sensor characteristics and performance", "inherent_difficulty": 3.5,
     "question": "What is true about repeatability?",
     "option_A": "It relates to measurement systems.",
     "option_B": "Repeatability is a fundamental concept.",
     "option_C": "It affects system performance.",
     "option_D": "It must be properly understood.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.6, "D": 1.8},
     "subtopic": "Repeatability",
     "explanation": "Repeatability is how consistently a sensor produces the same output."},
    {"question_id": "T05Q14", "topic": "Sensor characteristics and performance", "inherent_difficulty": 4.1,
     "question": "Which statement describes reproducibility?",
     "option_A": "Depends on implementation in typical industrial applications.",
     "option_B": "Is always constant, depending on specific system requirements.",
     "option_C": "Cannot be measured directly for most standard configurations.",
     "option_D": "Reproducibility is how consistently results match across dif.",
     "answer": "D", "distractor_strength": {"A": 1.2, "B": 1.8, "C": 1.6},
     "subtopic": "Reproducibility",
     "explanation": "Reproducibility is how consistently results match across different conditions."},
    {"question_id": "T05Q15", "topic": "Sensor characteristics and performance", "inherent_difficulty": 4.8,
     "question": "How does zero-point stability influence measurement?",
     "option_A": "All of the above.",
     "option_B": "Increases signal quality.",
     "option_C": "Affects system accuracy.",
     "option_D": "Reduces noise.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.6, "D": 1.2},
     "subtopic": "Zero-point stability",
     "explanation": "Zero-point stability ensures the sensor baseline remains constant."},
    {"question_id": "T05Q2", "topic": "Sensor characteristics and performance", "inherent_difficulty": 5.4,
     "question": "Which statement describes resolution definition?",
     "option_A": "Depends on implementation in typical industrial applications.",
     "option_B": "Cannot be measured directly for most standard configurations.",
     "option_C": "Resolution is the smallest detectable change in the measured.",
     "option_D": "Is always constant, depending on specific system requirements.",
     "answer": "C", "distractor_strength": {"A": 1.2, "B": 1.6, "D": 1.8},
     "subtopic": "Resolution definition",
     "explanation": "Resolution is the smallest detectable change in the measured quantity."},
    {"question_id": "T05Q3", "topic": "Sensor characteristics and performance", "inherent_difficulty": 6.0,
     "question": "How does sensitivity concept influence measurement?",
     "option_A": "All of the above.",
     "option_B": "Increases signal quality.",
     "option_C": "Affects system accuracy.",
     "option_D": "Reduces noise.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.6, "D": 1.2},
     "subtopic": "Sensitivity concept",
     "explanation": "Sensitivity is the ratio of output change to input change."},
    {"question_id": "T05Q4", "topic": "Sensor characteristics and performance", "inherent_difficulty": 6.7,
     "question": "When applying response time, engineers must consider:",
     "option_A": "Temperature effects.",
     "option_B": "Multiple considerations.",
     "option_C": "Environmental factors.",
     "option_D": "Frequency response.",
     "answer": "B", "distractor_strength": {"A": 1.2, "C": 1.6, "D": 1.4},
     "subtopic": "Response time",
     "explanation": "Response time is how quickly a sensor reacts to a change in measurand."},
    {"question_id": "T05Q5", "topic": "Sensor characteristics and performance", "inherent_difficulty": 7.3,
     "question": "What is true about dynamic range?",
     "option_A": "It relates to measurement systems.",
     "option_B": "Dynamic range is a fundamental concept.",
     "option_C": "It affects system performance.",
     "option_D": "It must be properly understood.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.6, "D": 1.8},
     "subtopic": "Dynamic range",
     "explanation": "Dynamic range is the ratio of maximum to minimum measurable values."},
    {"question_id": "T05Q6", "topic": "Sensor characteristics and performance", "inherent_difficulty": 7.9,
     "question": "Which statement describes hysteresis error?",
     "option_A": "Hysteresis causes different outputs for the same input depen.",
     "option_B": "Depends on implementation in typical industrial applications.",
     "option_C": "Cannot be measured directly for most standard configurations.",
     "option_D": "Is always constant, depending on specific system requirements.",
     "answer": "A", "distractor_strength": {"B": 1.2, "C": 1.6, "D": 1.8},
     "subtopic": "Hysteresis error",
     "explanation": "Hysteresis causes different outputs for the same input depending on approach direction."},
    {"question_id": "T05Q7", "topic": "Sensor characteristics and performance", "inherent_difficulty": 8.5,
     "question": "How does linearity specification influence measurement?",
     "option_A": "Reduces noise.",
     "option_B": "All of the above.",
     "option_C": "Affects system accuracy.",
     "option_D": "Increases signal quality.",
     "answer": "B", "distractor_strength": {"A": 1.2, "C": 1.6, "D": 1.4},
     "subtopic": "Linearity specification",
     "explanation": "Linearity indicates how closely output follows a straight line."},
    {"question_id": "T05Q8", "topic": "Sensor characteristics and performance", "inherent_difficulty": 9.2,
     "question": "When applying drift over time, engineers must consider:",
     "option_A": "Temperature effects.",
     "option_B": "Frequency response.",
     "option_C": "Environmental factors.",
     "option_D": "Multiple considerations.",
     "answer": "D", "distractor_strength": {"A": 1.2, "B": 1.4, "C": 1.6},
     "subtopic": "Drift over time",
     "explanation": "Drift is the gradual change in sensor output over extended operation."},
    {"question_id": "T05Q9", "topic": "Sensor characteristics and performance", "inherent_difficulty": 9.8,
     "question": "What is true about temperature coefficient?",
     "option_A": "It relates to measurement systems within the system.",
     "option_B": "Temperature coefficient is a fundamental concept.",
     "option_C": "It affects system performance under typical loads.",
     "option_D": "It must be properly understood in standard practice.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.6, "D": 1.8},
     "subtopic": "Temperature coefficient",
     "explanation": "Temperature coefficient describes how performance changes with temperature."},
    {"question_id": "T06Q1", "topic": "Logic gates and Boolean algebra", "inherent_difficulty": 1.0,
     "question": "What is true about and gate logic?",
     "option_A": "It relates to measurement systems.",
     "option_B": "AND gate logic is a fundamental concept.",
     "option_C": "It affects system performance.",
     "option_D": "It must be properly understood.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.6, "D": 1.8},
     "subtopic": "AND gate logic",
     "explanation": "AND gate outputs 1 only when all inputs are 1."},
    {"question_id": "T06Q10", "topic": "Logic gates and Boolean algebra", "inherent_difficulty": 1.6,
     "question": "Which statement describes distributive law?",
     "option_A": "A AND (B OR C) equals (A AND B) OR (A AND C).",
     "option_B": "Depends on implementation under typical loads.",
     "option_C": "Cannot be measured directly within the system.",
     "option_D": "Is always constant in practical scenarios.",
     "answer": "A", "distractor_strength": {"B": 1.2, "C": 1.6, "D": 1.8},
     "subtopic": "Distributive law",
     "explanation": "A AND (B OR C) equals (A AND B) OR (A AND C)."},
    {"question_id": "T06Q11", "topic": "Logic gates and Boolean algebra", "inherent_difficulty": 2.3,
     "question": "How does absorption law influence measurement?",
     "option_A": "Reduces noise.",
     "option_B": "All of the above.",
     "option_C": "Affects system accuracy.",
     "option_D": "Increases signal quality.",
     "answer": "B", "distractor_strength": {"A": 1.2, "C": 1.6, "D": 1.4},
     "subtopic": "Absorption law",
     "explanation": "A OR (A AND B) equals A."},
    {"question_id": "T06Q12", "topic": "Logic gates and Boolean algebra", "inherent_difficulty": 2.9,
     "question": "When applying idempotent law, engineers must consider:",
     "option_A": "Temperature effects.",
     "option_B": "Frequency response.",
     "option_C": "Environmental factors.",
     "option_D": "Multiple considerations.",
     "answer": "D", "distractor_strength": {"A": 1.2, "B": 1.4, "C": 1.6},
     "subtopic": "Idempotent law",
     "explanation": "A AND A equals A, A OR A equals A."},
    {"question_id": "T06Q13", "topic": "Logic gates and Boolean algebra", "inherent_difficulty": 3.5,
     "question": "What is true about complement law?",
     "option_A": "Complement law is a fundamental concept.",
     "option_B": "It relates to measurement systems.",
     "option_C": "It affects system performance.",
     "option_D": "It must be properly understood.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.6, "D": 1.8},
     "subtopic": "Complement law",
     "explanation": "A AND NOT(A) equals 0, A OR NOT(A) equals 1."},
    {"question_id": "T06Q14", "topic": "Logic gates and Boolean algebra", "inherent_difficulty": 4.1,
     "question": "Which statement describes double negation?",
     "option_A": "Depends on implementation.",
     "option_B": "Cannot be measured directly.",
     "option_C": "NOT(NOT(A)) equals A.",
     "option_D": "Is always constant.",
     "answer": "C", "distractor_strength": {"A": 1.2, "B": 1.6, "D": 1.8},
     "subtopic": "Double negation",
     "explanation": "NOT(NOT(A)) equals A."},
    {"question_id": "T06Q15", "topic": "Logic gates and Boolean algebra", "inherent_difficulty": 4.8,
     "question": "How does karnaugh map use influence measurement?",
     "option_A": "Reduces noise.",
     "option_B": "Increases signal quality.",
     "option_C": "Affects system accuracy.",
     "option_D": "All of the above.",
     "answer": "D", "distractor_strength": {"A": 1.2, "B": 1.4, "C": 1.6},
     "subtopic": "Karnaugh map use",
     "explanation": "Karnaugh maps simplify Boolean expressions visually."},
    {"question_id": "T06Q2", "topic": "Logic gates and Boolean algebra", "inherent_difficulty": 5.4,
     "question": "Which statement describes or gate function?",
     "option_A": "OR gate outputs 1 when at least one input is 1.",
     "option_B": "Depends on implementation in standard practice.",
     "option_C": "Cannot be measured directly under typical loads.",
     "option_D": "Is always constant in practical implementations.",
     "answer": "A", "distractor_strength": {"B": 1.2, "C": 1.6, "D": 1.8},
     "subtopic": "OR gate function",
     "explanation": "OR gate outputs 1 when at least one input is 1."},
    {"question_id": "T06Q3", "topic": "Logic gates and Boolean algebra", "inherent_difficulty": 6.0,
     "question": "How does not gate operation influence measurement?",
     "option_A": "Reduces noise.",
     "option_B": "Increases signal quality.",
     "option_C": "Affects system accuracy.",
     "option_D": "All of the above.",
     "answer": "D", "distractor_strength": {"A": 1.2, "B": 1.4, "C": 1.6},
     "subtopic": "NOT gate operation",
     "explanation": "NOT gate inverts the input logic level."},
    {"question_id": "T06Q4", "topic": "Logic gates and Boolean algebra", "inherent_difficulty": 6.7,
     "question": "When applying nand gate properties, engineers must consider:",
     "option_A": "Temperature effects.",
     "option_B": "Multiple considerations.",
     "option_C": "Environmental factors.",
     "option_D": "Frequency response.",
     "answer": "B", "distractor_strength": {"A": 1.2, "C": 1.6, "D": 1.4},
     "subtopic": "NAND gate properties",
     "explanation": "NAND gate outputs 0 only when all inputs are 1."},
    {"question_id": "T06Q5", "topic": "Logic gates and Boolean algebra", "inherent_difficulty": 7.3,
     "question": "What is true about nor gate behavior?",
     "option_A": "It must be properly understood.",
     "option_B": "It relates to measurement systems.",
     "option_C": "It affects system performance within the system.",
     "option_D": "NOR gate behavior is a fundamental concept.",
     "answer": "D", "distractor_strength": {"A": 1.8, "B": 1.4, "C": 1.6},
     "subtopic": "NOR gate behavior",
     "explanation": "NOR gate outputs 1 only when all inputs are 0."},
    {"question_id": "T06Q6", "topic": "Logic gates and Boolean algebra", "inherent_difficulty": 7.9,
     "question": "Which statement describes xor operation?",
     "option_A": "Depends on implementation.",
     "option_B": "Is always constant within the system.",
     "option_C": "Cannot be measured directly.",
     "option_D": "XOR gate outputs 1 when inputs differ.",
     "answer": "D", "distractor_strength": {"A": 1.2, "B": 1.8, "C": 1.6},
     "subtopic": "XOR operation",
     "explanation": "XOR gate outputs 1 when inputs differ."},
    {"question_id": "T06Q7", "topic": "Logic gates and Boolean algebra", "inherent_difficulty": 8.5,
     "question": "How does xnor equivalence influence measurement?",
     "option_A": "All of the above.",
     "option_B": "Increases signal quality.",
     "option_C": "Affects system accuracy.",
     "option_D": "Reduces noise.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.6, "D": 1.2},
     "subtopic": "XNOR equivalence",
     "explanation": "XNOR gate outputs 1 when inputs are identical."},
    {"question_id": "T06Q8", "topic": "Logic gates and Boolean algebra", "inherent_difficulty": 9.2,
     "question": "When applying de morgan first law, engineers must consider:",
     "option_A": "Temperature effects.",
     "option_B": "Frequency response.",
     "option_C": "Multiple considerations.",
     "option_D": "Environmental factors.",
     "answer": "C", "distractor_strength": {"A": 1.2, "B": 1.4, "D": 1.6},
     "subtopic": "De Morgan first law",
     "explanation": "NOT(A AND B) equals NOT(A) OR NOT(B)."},
    {"question_id": "T06Q9", "topic": "Logic gates and Boolean algebra", "inherent_difficulty": 9.8,
     "question": "What is true about de morgan second law?",
     "option_A": "De Morgan second law is a fundamental concept.",
     "option_B": "It relates to measurement systems.",
     "option_C": "It affects system performance within the system.",
     "option_D": "It must be properly understood under typical loads.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.6, "D": 1.8},
     "subtopic": "De Morgan second law",
     "explanation": "NOT(A OR B) equals NOT(A) AND NOT(B)."},
    {"question_id": "T07Q1", "topic": "Signal conditioning", "inherent_difficulty": 1.0,
     "question": "What is true about amplification purpose?",
     "option_A": "It affects system performance within the system.",
     "option_B": "It relates to measurement systems under typical loads.",
     "option_C": "Amplification purpose is a fundamental concept.",
     "option_D": "It must be properly understood in standard practice.",
     "answer": "C", "distractor_strength": {"A": 1.6, "B": 1.4, "D": 1.8},
     "subtopic": "Amplification purpose",
     "explanation": "Amplification increases small sensor signals to usable levels."},
    {"question_id": "T07Q10", "topic": "Signal conditioning", "inherent_difficulty": 1.6,
     "question": "Which statement describes notch filtering?",
     "option_A": "Depends on implementation in typical industrial applications.",
     "option_B": "Is always constant, depending on specific system requirements.",
     "option_C": "Cannot be measured directly for most standard configurations.",
     "option_D": "Notch filters strongly attenuate a specific narrow frequency.",
     "answer": "D", "distractor_strength": {"A": 1.2, "B": 1.8, "C": 1.6},
     "subtopic": "Notch filtering",
     "explanation": "Notch filters strongly attenuate a specific narrow frequency band."},
    {"question_id": "T07Q11", "topic": "Signal conditioning", "inherent_difficulty": 2.3,
     "question": "How does active filter design influence measurement?",
     "option_A": "Reduces noise.",
     "option_B": "Increases signal quality.",
     "option_C": "Affects system accuracy.",
     "option_D": "All of the above.",
     "answer": "D", "distractor_strength": {"A": 1.2, "B": 1.4, "C": 1.6},
     "subtopic": "Active filter design",
     "explanation": "Active filters use op-amps and provide gain and low output impedance."},
    {"question_id": "T07Q12", "topic": "Signal conditioning", "inherent_difficulty": 2.9,
     "question": "When applying passive filter design, engineers must consider:",
     "option_A": "Temperature effects.",
     "option_B": "Frequency response.",
     "option_C": "Environmental factors.",
     "option_D": "Multiple considerations.",
     "answer": "D", "distractor_strength": {"A": 1.2, "B": 1.4, "C": 1.6},
     "subtopic": "Passive filter design",
     "explanation": "Passive filters use only resistors, capacitors, and inductors."},
    {"question_id": "T07Q13", "topic": "Signal conditioning", "inherent_difficulty": 3.5,
     "question": "What is true about noise reduction?",
     "option_A": "It must be properly understood.",
     "option_B": "It relates to measurement systems.",
     "option_C": "It affects system performance.",
     "option_D": "Noise reduction is a fundamental concept.",
     "answer": "D", "distractor_strength": {"A": 1.8, "B": 1.4, "C": 1.6},
     "subtopic": "Noise reduction",
     "explanation": "Signal conditioning reduces noise by filtering and shielding."},
    {"question_id": "T07Q14", "topic": "Signal conditioning", "inherent_difficulty": 4.1,
     "question": "Which statement describes dynamic range expansion?",
     "option_A": "Depends on implementation in practical implementations.",
     "option_B": "Proper conditioning extends the usable dynamic range.",
     "option_C": "Cannot be measured directly in practical scenarios.",
     "option_D": "Is always constant across the entire operating range.",
     "answer": "B", "distractor_strength": {"A": 1.2, "C": 1.6, "D": 1.8},
     "subtopic": "Dynamic range expansion",
     "explanation": "Proper conditioning extends the usable dynamic range."},
    {"question_id": "T07Q15", "topic": "Signal conditioning", "inherent_difficulty": 4.8,
     "question": "How does analog-to-digital prep influence measurement?",
     "option_A": "Reduces noise.",
     "option_B": "Increases signal quality.",
     "option_C": "All of the above.",
     "option_D": "Affects system accuracy.",
     "answer": "C", "distractor_strength": {"A": 1.2, "B": 1.4, "D": 1.6},
     "subtopic": "Analog-to-digital prep",
     "explanation": "Signal conditioning prepares signals for digital conversion."},
    {"question_id": "T07Q2", "topic": "Signal conditioning", "inherent_difficulty": 5.4,
     "question": "Which statement describes filtering function?",
     "option_A": "Depends on implementation across the entire operating range.",
     "option_B": "Cannot be measured directly for most standard configurations.",
     "option_C": "Filters remove unwanted noise and interference from signals.",
     "option_D": "Is always constant, depending on specific system requirements.",
     "answer": "C", "distractor_strength": {"A": 1.2, "B": 1.6, "D": 1.8},
     "subtopic": "Filtering function",
     "explanation": "Filters remove unwanted noise and interference from signals."},
    {"question_id": "T07Q3", "topic": "Signal conditioning", "inherent_difficulty": 6.0,
     "question": "How does impedance matching influence measurement?",
     "option_A": "Reduces noise.",
     "option_B": "Increases signal quality.",
     "option_C": "All of the above.",
     "option_D": "Affects system accuracy.",
     "answer": "C", "distractor_strength": {"A": 1.2, "B": 1.4, "D": 1.6},
     "subtopic": "Impedance matching",
     "explanation": "Impedance matching prevents signal reflections and loading."},
    {"question_id": "T07Q4", "topic": "Signal conditioning", "inherent_difficulty": 6.7,
     "question": "When applying linearization, engineers must consider:",
     "option_A": "Temperature effects.",
     "option_B": "Frequency response.",
     "option_C": "Multiple considerations.",
     "option_D": "Environmental factors.",
     "answer": "C", "distractor_strength": {"A": 1.2, "B": 1.4, "D": 1.6},
     "subtopic": "Linearization",
     "explanation": "Linearization converts nonlinear sensor responses to linear relationships."},
    {"question_id": "T07Q5", "topic": "Signal conditioning", "inherent_difficulty": 7.3,
     "question": "What is true about offset removal?",
     "option_A": "Offset removal is a fundamental concept.",
     "option_B": "It relates to measurement systems.",
     "option_C": "It affects system performance.",
     "option_D": "It must be properly understood.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.6, "D": 1.8},
     "subtopic": "Offset removal",
     "explanation": "Offset removal corrects zero-point errors in sensor output."},
    {"question_id": "T07Q6", "topic": "Signal conditioning", "inherent_difficulty": 7.9,
     "question": "Which statement describes gain adjustment?",
     "option_A": "Depends on implementation during normal system operation.",
     "option_B": "Cannot be measured directly in practical implementations.",
     "option_C": "Gain adjustment scales signal amplitude to desired range.",
     "option_D": "Is always constant under standard operating conditions.",
     "answer": "C", "distractor_strength": {"A": 1.2, "B": 1.6, "D": 1.8},
     "subtopic": "Gain adjustment",
     "explanation": "Gain adjustment scales signal amplitude to desired range."},
    {"question_id": "T07Q7", "topic": "Signal conditioning", "inherent_difficulty": 8.5,
     "question": "How does low-pass filtering influence measurement?",
     "option_A": "Reduces noise.",
     "option_B": "Increases signal quality.",
     "option_C": "Affects system accuracy.",
     "option_D": "All of the above.",
     "answer": "D", "distractor_strength": {"A": 1.2, "B": 1.4, "C": 1.6},
     "subtopic": "Low-pass filtering",
     "explanation": "Low-pass filters block high frequencies above cutoff frequency."},
    {"question_id": "T07Q8", "topic": "Signal conditioning", "inherent_difficulty": 9.2,
     "question": "When applying high-pass filtering, engineers must consider:",
     "option_A": "Temperature effects.",
     "option_B": "Frequency response.",
     "option_C": "Multiple considerations.",
     "option_D": "Environmental factors.",
     "answer": "C", "distractor_strength": {"A": 1.2, "B": 1.4, "D": 1.6},
     "subtopic": "High-pass filtering",
     "explanation": "High-pass filters block low frequencies below cutoff frequency."},
    {"question_id": "T07Q9", "topic": "Signal conditioning", "inherent_difficulty": 9.8,
     "question": "What is true about band-pass filtering?",
     "option_A": "It relates to measurement systems.",
     "option_B": "Band-pass filtering is a fundamental concept.",
     "option_C": "It affects system performance within the system.",
     "option_D": "It must be properly understood under typical loads.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.6, "D": 1.8},
     "subtopic": "Band-pass filtering",
     "explanation": "Band-pass filters pass frequencies within a specific band."},
    {"question_id": "T08Q1", "topic": "Control systems", "inherent_difficulty": 1.0,
     "question": "What is true about feedback principle?",
     "option_A": "Feedback principle is a fundamental concept.",
     "option_B": "It relates to measurement systems.",
     "option_C": "It affects system performance within the system.",
     "option_D": "It must be properly understood under typical loads.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.6, "D": 1.8},
     "subtopic": "Feedback principle",
     "explanation": "Feedback compares output to reference and generates error signal."},
    {"question_id": "T08Q10", "topic": "Control systems", "inherent_difficulty": 1.6,
     "question": "Which statement describes system stability?",
     "option_A": "Stable systems do not oscillate or diverge indefinitely.",
     "option_B": "Depends on implementation in modern mechatronic systems.",
     "option_C": "Cannot be measured directly in practical implementations.",
     "option_D": "Is always constant under standard operating conditions.",
     "answer": "A", "distractor_strength": {"B": 1.2, "C": 1.6, "D": 1.8},
     "subtopic": "System stability",
     "explanation": "Stable systems do not oscillate or diverge indefinitely."},
    {"question_id": "T08Q11", "topic": "Control systems", "inherent_difficulty": 2.3,
     "question": "How does response overshoot influence measurement?",
     "option_A": "All of the above.",
     "option_B": "Increases signal quality.",
     "option_C": "Affects system accuracy.",
     "option_D": "Reduces noise.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.6, "D": 1.2},
     "subtopic": "Response overshoot",
     "explanation": "Overshoot is when output exceeds the reference value."},
    {"question_id": "T08Q12", "topic": "Control systems", "inherent_difficulty": 2.9,
     "question": "When applying rise time, engineers must consider:",
     "option_A": "Multiple considerations.",
     "option_B": "Frequency response.",
     "option_C": "Environmental factors.",
     "option_D": "Temperature effects.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.6, "D": 1.2},
     "subtopic": "Rise time",
     "explanation": "Rise time is how quickly output reaches the reference."},
    {"question_id": "T08Q13", "topic": "Control systems", "inherent_difficulty": 3.5,
     "question": "What is true about settling time?",
     "option_A": "Settling time is a fundamental concept.",
     "option_B": "It relates to measurement systems.",
     "option_C": "It affects system performance.",
     "option_D": "It must be properly understood.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.6, "D": 1.8},
     "subtopic": "Settling time",
     "explanation": "Settling time is how long system takes to reach steady state."},
    {"question_id": "T08Q14", "topic": "Control systems", "inherent_difficulty": 4.1,
     "question": "Which statement describes disturbance rejection?",
     "option_A": "Depends on implementation in practical scenarios.",
     "option_B": "Good control systems reject external disturbances.",
     "option_C": "Cannot be measured directly in standard practice.",
     "option_D": "Is always constant during normal system operation.",
     "answer": "B", "distractor_strength": {"A": 1.2, "C": 1.6, "D": 1.8},
     "subtopic": "Disturbance rejection",
     "explanation": "Good control systems reject external disturbances."},
    {"question_id": "T08Q15", "topic": "Control systems", "inherent_difficulty": 4.8,
     "question": "How does setpoint tracking influence measurement?",
     "option_A": "Reduces noise.",
     "option_B": "Increases signal quality.",
     "option_C": "All of the above.",
     "option_D": "Affects system accuracy.",
     "answer": "C", "distractor_strength": {"A": 1.2, "B": 1.4, "D": 1.6},
     "subtopic": "Setpoint tracking",
     "explanation": "Tracking ability measures how well output follows changes in reference."},
    {"question_id": "T08Q2", "topic": "Control systems", "inherent_difficulty": 5.4,
     "question": "Which statement describes error signal?",
     "option_A": "Error signal is the difference between desired and actual ou.",
     "option_B": "Depends on implementation in typical industrial applications.",
     "option_C": "Cannot be measured directly for most standard configurations.",
     "option_D": "Is always constant, depending on specific system requirements.",
     "answer": "A", "distractor_strength": {"B": 1.2, "C": 1.6, "D": 1.8},
     "subtopic": "Error signal",
     "explanation": "Error signal is the difference between desired and actual output."},
    {"question_id": "T08Q3", "topic": "Control systems", "inherent_difficulty": 6.0,
     "question": "How does closed-loop operation influence measurement?",
     "option_A": "All of the above.",
     "option_B": "Increases signal quality.",
     "option_C": "Affects system accuracy.",
     "option_D": "Reduces noise.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.6, "D": 1.2},
     "subtopic": "Closed-loop operation",
     "explanation": "Closed-loop systems use feedback to correct errors automatically."},
    {"question_id": "T08Q4", "topic": "Control systems", "inherent_difficulty": 6.7,
     "question": "When applying open-loop operation, engineers must consider:",
     "option_A": "Temperature effects.",
     "option_B": "Multiple considerations.",
     "option_C": "Environmental factors.",
     "option_D": "Frequency response.",
     "answer": "B", "distractor_strength": {"A": 1.2, "C": 1.6, "D": 1.4},
     "subtopic": "Open-loop operation",
     "explanation": "Open-loop systems act without feedback information."},
    {"question_id": "T08Q5", "topic": "Control systems", "inherent_difficulty": 7.3,
     "question": "What is true about reference input?",
     "option_A": "It relates to measurement systems.",
     "option_B": "Reference input is a fundamental concept.",
     "option_C": "It affects system performance.",
     "option_D": "It must be properly understood.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.6, "D": 1.8},
     "subtopic": "Reference input",
     "explanation": "Reference input specifies the desired system output value."},
    {"question_id": "T08Q6", "topic": "Control systems", "inherent_difficulty": 7.9,
     "question": "Which statement describes actuator role?",
     "option_A": "Depends on implementation during normal system operation.",
     "option_B": "Actuators apply corrective forces based on control signal.",
     "option_C": "Cannot be measured directly under specified design limits.",
     "option_D": "Is always constant under standard operating conditions.",
     "answer": "B", "distractor_strength": {"A": 1.2, "C": 1.6, "D": 1.8},
     "subtopic": "Actuator role",
     "explanation": "Actuators apply corrective forces based on control signal."},
    {"question_id": "T08Q7", "topic": "Control systems", "inherent_difficulty": 8.5,
     "question": "How does sensor role influence measurement?",
     "option_A": "Reduces noise.",
     "option_B": "Increases signal quality.",
     "option_C": "All of the above.",
     "option_D": "Affects system accuracy.",
     "answer": "C", "distractor_strength": {"A": 1.2, "B": 1.4, "D": 1.6},
     "subtopic": "Sensor role",
     "explanation": "Sensors measure actual system output for feedback."},
    {"question_id": "T08Q8", "topic": "Control systems", "inherent_difficulty": 9.2,
     "question": "When applying transient response, engineers must consider:",
     "option_A": "Multiple considerations.",
     "option_B": "Frequency response.",
     "option_C": "Environmental factors.",
     "option_D": "Temperature effects.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.6, "D": 1.2},
     "subtopic": "Transient response",
     "explanation": "Transient response describes how system reaches steady state."},
    {"question_id": "T08Q9", "topic": "Control systems", "inherent_difficulty": 9.8,
     "question": "What is true about steady-state error?",
     "option_A": "Steady-state error is a fundamental concept.",
     "option_B": "It relates to measurement systems.",
     "option_C": "It affects system performance within the system.",
     "option_D": "It must be properly understood under typical loads.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.6, "D": 1.8},
     "subtopic": "Steady-state error",
     "explanation": "Steady-state error is the final error after system settles."}
]
