"""Question bank part 2/5 - topics 9..17 (135 MCQs, 15 per topic).

Each entry: question_id, topic, inherent_difficulty (1.0..9.8), question, four
options, answer, distractor_strength, explanation, subtopic, source.
Grounded in R.K. Rajput, "A Textbook of Mechatronics".
Expanded to 15 questions per topic with balanced option lengths.
"""

QUESTIONS = [
    {"question_id": "T09Q1", "topic": "Measurement systems", "inherent_difficulty": 1.0,
     "question": "The three basic functional elements of a measurement system are:",
     "option_A": "Sensor, signal conditioner, and display/recorder.",
     "option_B": "Motor, gearbox, and shaft in practical scenarios.",
     "option_C": "Resistor, capacitor, inductor under typical loads.",
     "option_D": "CPU, RAM, ROM in typical industrial applications.",
     "answer": "A", "distractor_strength": {"B": 1.2, "C": 1.3, "D": 1.4},
     "subtopic": "functional elements",
     "explanation": "A measurement system has a sensing element, a signal-conditioning/processing element and a data presentation element."},
    {"question_id": "T09Q10", "topic": "Measurement systems", "inherent_difficulty": 1.6,
     "question": "The 'reproducibility' of a measurement means:",
     "option_A": "The instrument displays digits indefinitely during normal system operation.",
     "option_B": "The same result is obtained when the same measurand is measured repeatedly.",
     "option_C": "Accuracy automatically improves over time for most standard configurations.",
     "option_D": "Expensive equipment always gives this property in practical implementations.",
     "answer": "B", "distractor_strength": {"A": 1.3, "C": 1.5, "D": 1.4},
     "subtopic": "reproducibility",
     "explanation": "Reproducibility (precision) is consistency of repeated measurements of the same quantity."},
    {"question_id": "T09Q11", "topic": "Measurement systems", "inherent_difficulty": 2.3,
     "question": "A measurement system displays a reading that is 5% higher than expected on average. This indicates:",
     "option_A": "Random error only during normal system operation.",
     "option_B": "No error at all for most standard configurations.",
     "option_C": "Resolution error exclusively under typical loads.",
     "option_D": "Systematic (bias) error in the measurement chain.",
     "answer": "D", "distractor_strength": {"A": 1.7, "B": 1.8, "C": 1.6},
     "subtopic": "bias detection",
     "explanation": "A consistent offset suggests a systematic error that affects all readings identically and can be corrected."},
    {"question_id": "T09Q12", "topic": "Measurement systems", "inherent_difficulty": 2.9,
     "question": "The 'response time' of a measurement system is the time required to:",
     "option_A": "Reach a stable output after input change (typically to 63% for first-order).",
     "option_B": "Turn the instrument on, depending on specific system requirements.",
     "option_C": "Generate the display under standard operating conditions and within the system.",
     "option_D": "Calibrate against a standard in typical industrial applications.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.5, "D": 1.6},
     "subtopic": "response time",
     "explanation": "Response time characterizes the speed at which a measurement instrument tracks input changes."},
    {"question_id": "T09Q13", "topic": "Measurement systems", "inherent_difficulty": 3.5,
     "question": "How does increasing the 'filter bandwidth' of a measurement system affect error?",
     "option_A": "Always eliminates all noise during normal system operation.",
     "option_B": "Improves accuracy at all frequencies in practical scenarios.",
     "option_C": "Has no effect on measurements under specified design limits.",
     "option_D": "Reduces noise but can introduce phase lag and slow response.",
     "answer": "D", "distractor_strength": {"A": 1.4, "B": 1.5, "C": 1.6},
     "subtopic": "filter trade-off",
     "explanation": "Bandwidth and attenuation trade off; wider bandwidth passes more noise but has faster response."},
    {"question_id": "T09Q14", "topic": "Measurement systems", "inherent_difficulty": 4.1,
     "question": "A measurement system uses three independent sensors. To combine their readings optimally for accuracy, the best approach is:",
     "option_A": "Average them, but weight by sensor reliability/uncertainty.",
     "option_B": "Use the highest reading only under specified design limits.",
     "option_C": "Use the median value under standard operating conditions.",
     "option_D": "Discard the lowest reading during normal system operation.",
     "answer": "A", "distractor_strength": {"B": 1.5, "C": 1.6, "D": 1.7},
     "subtopic": "sensor fusion",
     "explanation": "Weighted averaging by inverse variance (reliability) gives the minimum-variance estimate."},
    {"question_id": "T09Q15", "topic": "Measurement systems", "inherent_difficulty": 4.8,
     "question": "In a metrological chain, the ratio of the reference standard uncertainty to device-under-test uncertainty should be:",
     "option_A": "At least 1:1 or greater under standard operating conditions.",
     "option_B": "Less than 10:1 always in typical industrial applications.",
     "option_C": "At least 3:1 (ideally 4:1 or better) for valid traceability.",
     "option_D": "Exactly 1:1 for perfect accuracy in practical implementations.",
     "answer": "C", "distractor_strength": {"A": 1.5, "B": 1.7, "D": 1.6},
     "subtopic": "metrological hierarchy",
     "explanation": "Reference must be 3-10x better than device being calibrated to establish valid traceability."},
    {"question_id": "T09Q2", "topic": "Measurement systems", "inherent_difficulty": 5.4,
     "question": "'Accuracy' and 'precision' differ in that:",
     "option_A": "They mean exactly the same thing, depending on specific system requirements.",
     "option_B": "Precision is closeness to true value; accuracy is repeatability within the system.",
     "option_C": "Accuracy is closeness to the true value; precision is repeatability of readings.",
     "option_D": "Both refer only to resolution under standard operating conditions and under typical loads.",
     "answer": "C", "distractor_strength": {"A": 1.6, "B": 2.5, "D": 1.7},
     "subtopic": "accuracy vs precision",
     "explanation": "Accuracy = nearness to true value; precision = scatter/repeatability. A system can be precise but inaccurate."},
    {"question_id": "T09Q3", "topic": "Measurement systems", "inherent_difficulty": 6.0,
     "question": "A voltmeter with finite (non-infinite) input resistance connected across a high-resistance source produces a 'loading error', which is an example of:",
     "option_A": "A random error in practical scenarios.",
     "option_B": "A quantization error under typical loads.",
     "option_C": "A systematic interfering/modifying error.",
     "option_D": "Hysteresis under specified design limits.",
     "answer": "C", "distractor_strength": {"A": 2.2, "B": 1.6, "D": 1.5},
     "subtopic": "loading error",
     "explanation": "Loading is a repeatable systematic error: the instrument draws current and changes the quantity being measured."},
    {"question_id": "T09Q4", "topic": "Measurement systems", "inherent_difficulty": 6.7,
     "question": "A length is found from L = a + b where a = 50 +/- 0.3 mm and b = 30 +/- 0.4 mm (independent random errors). The standard uncertainty in L is about:",
     "option_A": "0.7 mm.",
     "option_B": "0.1 mm.",
     "option_C": "0.5 mm.",
     "option_D": "0.35 mm.",
     "answer": "C", "distractor_strength": {"A": 2.4, "B": 1.6, "D": 1.9},
     "subtopic": "error propagation",
     "explanation": "For a sum of independent errors, uncertainties add in quadrature: sqrt(0.3^2 + 0.4^2) = sqrt(0.25) = 0.5 mm."},
    {"question_id": "T09Q5", "topic": "Measurement systems", "inherent_difficulty": 7.3,
     "question": "What is the primary purpose of a measurement system?",
     "option_A": "To convert physical quantities into usable information.",
     "option_B": "To generate electrical power continuously within the system.",
     "option_C": "To amplify noise signals indefinitely under typical loads.",
     "option_D": "To create heat for warming in practical implementations.",
     "answer": "A", "distractor_strength": {"B": 1.3, "C": 1.4, "D": 1.2},
     "subtopic": "purpose",
     "explanation": "Measurement systems acquire, process and present physical data for observation and control."},
    {"question_id": "T09Q6", "topic": "Measurement systems", "inherent_difficulty": 7.9,
     "question": "The sensing element of a measurement system responds to:",
     "option_A": "The ambient noise in practical implementations.",
     "option_B": "The display only in modern mechatronic systems.",
     "option_C": "The power supply voltage in standard practice.",
     "option_D": "The measurand (physical input being measured).",
     "answer": "D", "distractor_strength": {"A": 1.3, "B": 1.4, "C": 1.5},
     "subtopic": "sensor response",
     "explanation": "The sensor directly interacts with the measurand and produces an initial response signal."},
    {"question_id": "T09Q7", "topic": "Measurement systems", "inherent_difficulty": 8.5,
     "question": "The 'range' of a measurement instrument is:",
     "option_A": "The minimum detectable input change within the system.",
     "option_B": "The response time in milliseconds under typical loads.",
     "option_C": "The maximum output voltage only in standard practice.",
     "option_D": "The span of input values it can measure (min to max).",
     "answer": "D", "distractor_strength": {"A": 1.5, "B": 1.4, "C": 1.6},
     "subtopic": "range definition",
     "explanation": "Range specifies the minimum and maximum measurand values the instrument can handle."},
    {"question_id": "T09Q8", "topic": "Measurement systems", "inherent_difficulty": 9.2,
     "question": "What distinguishes 'static' calibration from 'dynamic' calibration?",
     "option_A": "Dynamic cannot be used for sensors, depending on specific system requirements.",
     "option_B": "Static is more accurate than dynamic always under standard operating conditions.",
     "option_C": "Static uses a constant input; dynamic varies the input to test frequency response.",
     "option_D": "They are exactly the same procedure in typical industrial applications.",
     "answer": "C", "distractor_strength": {"A": 1.6, "B": 1.5, "D": 1.4},
     "subtopic": "calibration types",
     "explanation": "Static calibration uses constant inputs to establish DC characteristics; dynamic tests response to time-varying inputs."},
    {"question_id": "T09Q9", "topic": "Measurement systems", "inherent_difficulty": 9.8,
     "question": "A sensor's 'time constant' affects its:",
     "option_A": "Maximum measurable value.",
     "option_B": "Speed of response to input changes.",
     "option_C": "Sensitivity to temperature.",
     "option_D": "Output color only within the system.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.5, "D": 1.6},
     "subtopic": "time constant",
     "explanation": "Time constant determines how quickly the sensor output settles to a new equilibrium value after input change."},
    {"question_id": "T10Q1", "topic": "Position and displacement sensors", "inherent_difficulty": 1.0,
     "question": "A rotary potentiometer is most directly used to measure:",
     "option_A": "Light intensity.",
     "option_B": "Fluid pressure.",
     "option_C": "Shaft angular position.",
     "option_D": "Temperature.",
     "answer": "C", "distractor_strength": {"A": 1.2, "B": 1.5, "D": 1.3},
     "subtopic": "potentiometer",
     "explanation": "The wiper voltage of a rotary potentiometer is proportional to shaft angle."},
    {"question_id": "T10Q10", "topic": "Position and displacement sensors", "inherent_difficulty": 1.6,
     "question": "Non-linearity in a capacitive displacement sensor arises because capacitance varies as:",
     "option_A": "A linear function of separation distance for most standard configurations.",
     "option_B": "Constant independent of geometry, depending on specific system requirements.",
     "option_C": "The square of distance under standard operating conditions and within the system.",
     "option_D": "The reciprocal (inverse) of separation distance, so changes are nonlinear.",
     "answer": "D", "distractor_strength": {"A": 1.6, "B": 1.5, "C": 1.7},
     "subtopic": "capacitive nonlinearity",
     "explanation": "C = \u03b5\u2080A/d shows C \u221d 1/d, so equal displacement changes produce unequal capacitance changes."},
    {"question_id": "T10Q11", "topic": "Position and displacement sensors", "inherent_difficulty": 2.3,
     "question": "An incremental optical encoder requires post-processing to determine absolute position because:",
     "option_A": "It always gives the absolute value in practical implementations.",
     "option_B": "It only outputs relative motion pulses, not position identity.",
     "option_C": "It cannot measure at all under standard operating conditions.",
     "option_D": "No post-processing is ever needed in modern mechatronic systems.",
     "answer": "B", "distractor_strength": {"A": 1.5, "C": 1.4, "D": 1.6},
     "subtopic": "incremental limitation",
     "explanation": "Incremental encoders track changes (delta position); absolute encoders directly encode position at each spot."},
    {"question_id": "T10Q12", "topic": "Position and displacement sensors", "inherent_difficulty": 2.9,
     "question": "Backlash in a mechanical linkage connected to a position sensor causes:",
     "option_A": "Hysteresis: different output for same position depending on approach direction.",
     "option_B": "No measurable effect, depending on specific system requirements and within the system.",
     "option_C": "Increase in resolution only under standard operating conditions and under typical loads.",
     "option_D": "Perfect accuracy always in typical industrial applications and in standard practice.",
     "answer": "A", "distractor_strength": {"B": 1.5, "C": 1.6, "D": 1.4},
     "subtopic": "backlash",
     "explanation": "Mechanical play (backlash) creates a dead-band and hysteresis that degrades sensor accuracy and repeatability."},
    {"question_id": "T10Q13", "topic": "Position and displacement sensors", "inherent_difficulty": 3.5,
     "question": "An absolute optical encoder uses multiple tracks coded in Gray code to:",
     "option_A": "Increase the number of parts needed, depending on specific system requirements.",
     "option_B": "Ensure only one bit changes between adjacent positions, avoiding ambiguous glitches.",
     "option_C": "Make it slower than binary under standard operating conditions and within the system.",
     "option_D": "Eliminate the need for any sensor in typical industrial applications and under typical loads.",
     "answer": "B", "distractor_strength": {"A": 1.5, "C": 1.6, "D": 1.4},
     "subtopic": "Gray code benefit",
     "explanation": "Gray code's single-bit transitions prevent momentary invalid codes at track boundaries during transitions."},
    {"question_id": "T10Q14", "topic": "Position and displacement sensors", "inherent_difficulty": 4.1,
     "question": "A differential LVDT (with two identical LVDT cores back-to-back) improves measurement by:",
     "option_A": "Canceling common-mode errors (temp, excitation variations) while amplifying the measurement.",
     "option_B": "Doubling the weight of the sensor, depending on specific system requirements and within the system.",
     "option_C": "Making it impossible to use under standard operating conditions and in practical scenarios.",
     "option_D": "Eliminating all noise instantly in typical industrial applications and in standard practice.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.5, "D": 1.6},
     "subtopic": "differential LVDT",
     "explanation": "Opposite cores give complementary outputs; differential configuration rejects common-mode interference."},
    {"question_id": "T10Q15", "topic": "Position and displacement sensors", "inherent_difficulty": 4.8,
     "question": "A precision position measurement system using multiple sensors (redundancy) primarily serves to:",
     "option_A": "Increase cost unnecessarily, depending on specific system requirements.",
     "option_B": "Eliminate the need for calibration under standard operating conditions.",
     "option_C": "Slow down the measurement in typical industrial applications and within the system.",
     "option_D": "Detect and isolate faults; improve overall accuracy via weighted averaging.",
     "answer": "D", "distractor_strength": {"A": 1.5, "B": 1.6, "C": 1.4},
     "subtopic": "sensor redundancy",
     "explanation": "Redundant channels enable fault detection and optimal fusion to minimize total measurement uncertainty."},
    {"question_id": "T10Q2", "topic": "Position and displacement sensors", "inherent_difficulty": 5.4,
     "question": "An LVDT (linear variable differential transformer) produces an output that is:",
     "option_A": "An AC voltage whose amplitude depends on core displacement and phase indicates direction.",
     "option_B": "A DC voltage proportional to temperature, depending on specific system requirements.",
     "option_C": "A digital pulse train under standard operating conditions and in practical implementations.",
     "option_D": "Constant regardless of core position in typical industrial applications and within the system.",
     "answer": "A", "distractor_strength": {"B": 1.5, "C": 1.8, "D": 1.6},
     "subtopic": "LVDT",
     "explanation": "An LVDT's two secondaries give a differential AC output proportional to displacement; the phase relative to excitation shows direction."},
    {"question_id": "T10Q3", "topic": "Position and displacement sensors", "inherent_difficulty": 6.0,
     "question": "A capacitive displacement sensor with parallel plates increases its capacitance when:",
     "option_A": "The plate separation increases.",
     "option_B": "The plate separation decreases.",
     "option_C": "The dielectric is removed.",
     "option_D": "The plate area decreases.",
     "answer": "B", "distractor_strength": {"A": 2.5, "C": 1.6, "D": 2.0},
     "subtopic": "capacitive sensor",
     "explanation": "C = epsilon A / d, so capacitance rises as separation d falls (and the relationship is nonlinear)."},
    {"question_id": "T10Q4", "topic": "Position and displacement sensors", "inherent_difficulty": 6.7,
     "question": "An LVDT is excited at 5 kHz. To recover a clean DC displacement signal with correct sign, the output is processed by:",
     "option_A": "A simple half-wave rectifier, depending on specific system requirements.",
     "option_B": "A comparator only under standard operating conditions and within the system.",
     "option_C": "An XOR gate in typical industrial applications and in practical scenarios.",
     "option_D": "A phase-sensitive (synchronous) demodulator followed by a low-pass filter.",
     "answer": "D", "distractor_strength": {"A": 2.3, "B": 1.9, "C": 1.5},
     "subtopic": "LVDT demodulation",
     "explanation": "Synchronous (phase-sensitive) detection referenced to the excitation preserves direction information and rejects noise, then low-pass filtering gives a DC output."},
    {"question_id": "T10Q5", "topic": "Position and displacement sensors", "inherent_difficulty": 7.3,
     "question": "What is the main advantage of an optical encoder over a mechanical encoder?",
     "option_A": "It costs less money always in practical scenarios.",
     "option_B": "No moving parts in contact; no wear from friction.",
     "option_C": "It works only in darkness in standard practice.",
     "option_D": "It requires no power supply under typical loads.",
     "answer": "B", "distractor_strength": {"A": 1.5, "C": 1.4, "D": 1.3},
     "subtopic": "optical advantage",
     "explanation": "Optical encoders eliminate mechanical sliding contact, removing friction wear and improving life."},
    {"question_id": "T10Q6", "topic": "Position and displacement sensors", "inherent_difficulty": 7.9,
     "question": "A linear variable differential transformer (LVDT) is preferred for displacement measurement because:",
     "option_A": "It is cheap to manufacture under standard operating conditions.",
     "option_B": "It has a moving core for contactless operation and high linearity.",
     "option_C": "It generates digital output directly in practical implementations.",
     "option_D": "It works at any temperature without error in practical scenarios.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.5, "D": 1.3},
     "subtopic": "LVDT advantage",
     "explanation": "The transformer's contactless core eliminates friction, hysteresis and wear, giving high linearity and repeatability."},
    {"question_id": "T10Q7", "topic": "Position and displacement sensors", "inherent_difficulty": 8.5,
     "question": "The 'null position' of an LVDT is the location where the output voltage is:",
     "option_A": "Approximately zero (midpoint core position).",
     "option_B": "Minimum (most negative) under typical loads.",
     "option_C": "Maximum (most positive) in standard practice.",
     "option_D": "At the supply voltage in practical scenarios.",
     "answer": "A", "distractor_strength": {"B": 1.6, "C": 1.7, "D": 1.5},
     "subtopic": "null position",
     "explanation": "At null position the core is centered, giving maximum rejection of excitation carrier and minimum differential output."},
    {"question_id": "T10Q8", "topic": "Position and displacement sensors", "inherent_difficulty": 9.2,
     "question": "A draw-wire displacement sensor converts linear motion by:",
     "option_A": "Using piezoelectric elements stretched by motion for most standard configurations.",
     "option_B": "Detecting magnetic flux density, depending on specific system requirements.",
     "option_C": "Measuring capacitance change only under standard operating conditions.",
     "option_D": "Having a retractable wire attached to a rotating potentiometer on a spring pulley.",
     "answer": "D", "distractor_strength": {"A": 1.5, "B": 1.4, "C": 1.6},
     "subtopic": "draw-wire sensor",
     "explanation": "The wire extends/retracts with the target; the pulley rotates a potentiometer or encoder proportionally to distance."},
    {"question_id": "T10Q9", "topic": "Position and displacement sensors", "inherent_difficulty": 9.8,
     "question": "A Hall-effect sensor measures position by detecting:",
     "option_A": "Light reflections from the target surface.",
     "option_B": "Changes in magnetic field perpendicular to current.",
     "option_C": "Temperature variations only in practical scenarios.",
     "option_D": "Mechanical pressure directly in standard practice.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.5, "D": 1.3},
     "subtopic": "Hall effect",
     "explanation": "The Hall voltage (perpendicular to current and field) enables contactless sensing of magnet position."},
    {"question_id": "T11Q1", "topic": "Temperature sensors", "inherent_difficulty": 1.0,
     "question": "A bimetallic strip bends with temperature mainly because the two bonded metals have different:",
     "option_A": "Electrical resistances.",
     "option_B": "Coefficients of thermal expansion.",
     "option_C": "Magnetic permeabilities.",
     "option_D": "Densities only within the system.",
     "answer": "B", "distractor_strength": {"A": 1.8, "C": 1.3, "D": 1.5},
     "subtopic": "bimetallic strip",
     "explanation": "Unequal expansion of the bonded metals causes the strip to curve as temperature changes."},
    {"question_id": "T11Q10", "topic": "Temperature sensors", "inherent_difficulty": 1.6,
     "question": "The Seebeck coefficient (in microvolts per Celsius) of a Type-K thermocouple is approximately:",
     "option_A": "4.1 millivolts per degree Celsius.",
     "option_B": "410 microvolts per degree Celsius.",
     "option_C": "41 microvolts per degree Celsius.",
     "option_D": "0.41 microvolts per degree Celsius.",
     "answer": "C", "distractor_strength": {"A": 1.6, "B": 1.5, "D": 1.4},
     "subtopic": "Seebeck coefficient",
     "explanation": "Type-K (Chromel/Alumel) has ~41 \u00b5V/\u00b0C sensitivity, making it a popular general-purpose thermocouple."},
    {"question_id": "T11Q11", "topic": "Temperature sensors", "inherent_difficulty": 2.3,
     "question": "Thermal lag (time delay) in a temperature sensor arises primarily from:",
     "option_A": "Electrical resistance of the wires under standard operating conditions.",
     "option_B": "Non-linearity of the calibration, depending on specific system requirements.",
     "option_C": "The thermal mass of the sensor and finite heat transfer to the measurand.",
     "option_D": "The color of the sensor housing in typical industrial applications.",
     "answer": "C", "distractor_strength": {"A": 1.4, "B": 1.5, "D": 1.3},
     "subtopic": "thermal lag",
     "explanation": "Thermal time constant depends on sensor mass and thermal conductance between it and the medium."},
    {"question_id": "T11Q12", "topic": "Temperature sensors", "inherent_difficulty": 2.9,
     "question": "A thermistor with negative temperature coefficient (NTC) means its resistance:",
     "option_A": "Increases as temperature rises.",
     "option_B": "Decreases as temperature rises.",
     "option_C": "Remains constant with temperature.",
     "option_D": "Becomes infinite above 100 degrees Celsius.",
     "answer": "B", "distractor_strength": {"A": 1.5, "C": 1.4, "D": 1.3},
     "subtopic": "NTC thermistor",
     "explanation": "Negative coefficient: dR/dT < 0; higher temperature means lower resistance (opposite of RTD)."},
    {"question_id": "T11Q13", "topic": "Temperature sensors", "inherent_difficulty": 3.5,
     "question": "Self-heating error in a temperature sensor occurs when:",
     "option_A": "The sensor is externally heated, depending on specific system requirements and under standard operating conditions.",
     "option_B": "Excitation current flowing through resistance dissipates heat, raising the sensor above the true medium temperature.",
     "option_C": "The display malfunctions in typical industrial applications and across the entire operating range and within the system.",
     "option_D": "No error can occur from heating for most standard configurations and during normal system operation and under typical loads.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.5, "D": 1.3},
     "subtopic": "self-heating",
     "explanation": "I\u00b2R dissipation in the sensor element can warm it relative to the surrounding medium, biasing measurement."},
    {"question_id": "T11Q14", "topic": "Temperature sensors", "inherent_difficulty": 4.1,
     "question": "A platinum resistance thermometer (PRT) uses platinum because it:",
     "option_A": "Is the cheapest metal available in modern mechatronic systems.",
     "option_B": "Cannot be oxidized, depending on specific system requirements.",
     "option_C": "Has excellent linearity, stability and wide temperature range.",
     "option_D": "Works at any temperature without error in practical scenarios.",
     "answer": "C", "distractor_strength": {"A": 1.4, "B": 1.5, "D": 1.3},
     "subtopic": "platinum RTD",
     "explanation": "Platinum's reproducible, stable resistance change and wide operating range make it the RTD standard."},
    {"question_id": "T11Q15", "topic": "Temperature sensors", "inherent_difficulty": 4.8,
     "question": "For a sensor with time constant tau measuring a linear temperature ramp dT/dt = rate, the steady-state measurement lag is:",
     "option_A": "Zero always, depending on specific system requirements.",
     "option_B": "Always 63% of the true value in typical industrial applications.",
     "option_C": "Independent of the input rate across the entire operating range.",
     "option_D": "tau \u00d7 (dT/dt), proportional to both time constant and ramp rate.",
     "answer": "D", "distractor_strength": {"A": 1.5, "B": 1.4, "C": 1.6},
     "subtopic": "ramp response lag",
     "explanation": "First-order lag = tau \u00d7 rate: sensor lags behind a ramp by an amount proportional to time constant and input slew rate."},
    {"question_id": "T11Q2", "topic": "Temperature sensors", "inherent_difficulty": 5.4,
     "question": "Compared with an RTD, a thermistor typically has:",
     "option_A": "A small, linear, positive temperature coefficient within the system.",
     "option_B": "A large, nonlinear resistance change (often negative coefficient).",
     "option_C": "No temperature dependence, depending on specific system requirements.",
     "option_D": "An output in volts directly under standard operating conditions.",
     "answer": "B", "distractor_strength": {"A": 2.4, "C": 1.3, "D": 1.6},
     "subtopic": "thermistor vs RTD",
     "explanation": "NTC thermistors show a large, highly nonlinear resistance fall with temperature; RTDs are smaller and far more linear."},
    {"question_id": "T11Q3", "topic": "Temperature sensors", "inherent_difficulty": 6.0,
     "question": "A platinum RTD (Pt100) has a resistance of 100 ohm at 0 C and alpha = 0.00385 /C. Its resistance at 100 C is about:",
     "option_A": "138.5 ohm.",
     "option_B": "100.4 ohm.",
     "option_C": "385 ohm.",
     "option_D": "103.85 ohm.",
     "answer": "A", "distractor_strength": {"B": 1.8, "C": 2.2, "D": 2.4},
     "subtopic": "RTD calculation",
     "explanation": "R = R0(1 + alpha x dT) = 100(1 + 0.00385 x 100) = 138.5 ohm."},
    {"question_id": "T11Q4", "topic": "Temperature sensors", "inherent_difficulty": 6.7,
     "question": "Lead-wire resistance causes errors in a 2-wire RTD. The standard remedy is to use a 3- or 4-wire connection, which works by:",
     "option_A": "Increasing the excitation current for most standard configurations.",
     "option_B": "Cancelling/eliminating the lead resistance from the measured value.",
     "option_C": "Adding a thermistor in series under standard operating conditions.",
     "option_D": "Doubling the RTD resistance in typical industrial applications.",
     "answer": "B", "distractor_strength": {"A": 1.7, "C": 1.6, "D": 1.8},
     "subtopic": "lead-wire compensation",
     "explanation": "3-/4-wire schemes route the sense connection so lead-wire drops cancel (3-wire) or are excluded by sensing across the element with no current in the sense leads (4-wire)."},
    {"question_id": "T11Q5", "topic": "Temperature sensors", "inherent_difficulty": 7.3,
     "question": "What physical property of a thermocouple enables it to measure temperature?",
     "option_A": "Mechanical vibration, depending on specific system requirements.",
     "option_B": "Magnetic field changes only under standard operating conditions.",
     "option_C": "Light absorption characteristics in typical industrial applications.",
     "option_D": "The Seebeck effect: EMF generation at a junction of dissimilar metals.",
     "answer": "D", "distractor_strength": {"A": 1.2, "B": 1.3, "C": 1.4},
     "subtopic": "Seebeck principle",
     "explanation": "Seebeck effect: a temperature-dependent EMF develops at the junction of two dissimilar conductors."},
    {"question_id": "T11Q6", "topic": "Temperature sensors", "inherent_difficulty": 7.9,
     "question": "The primary disadvantage of a bimetallic strip sensor is its:",
     "option_A": "Inability to measure any temperature within the system.",
     "option_B": "Instant response time during normal system operation.",
     "option_C": "Requirement for external power in practical scenarios.",
     "option_D": "Nonlinearity and mechanical hysteresis from friction.",
     "answer": "D", "distractor_strength": {"A": 1.3, "B": 1.4, "C": 1.5},
     "subtopic": "bimetallic limitations",
     "explanation": "Mechanical friction and play in the bimetallic strip cause hysteresis and limit accuracy."},
    {"question_id": "T11Q7", "topic": "Temperature sensors", "inherent_difficulty": 8.5,
     "question": "A thermistor's 'B-value' (or 'beta') parameter characterizes its:",
     "option_A": "Temperature sensitivity (slope of resistance vs. temperature).",
     "option_B": "Maximum temperature limit only during normal system operation.",
     "option_C": "Color and packaging, depending on specific system requirements.",
     "option_D": "Power consumption rating under standard operating conditions.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.5, "D": 1.3},
     "subtopic": "B-value",
     "explanation": "B-value (in Kelvin) quantifies the thermistor's resistance-temperature relationship."},
    {"question_id": "T11Q8", "topic": "Temperature sensors", "inherent_difficulty": 9.2,
     "question": "Cold-junction compensation in thermocouple measurement is necessary because:",
     "option_A": "It cools the sensor automatically under standard operating conditions.",
     "option_B": "The measured EMF depends on the temperature difference between junctions.",
     "option_C": "It eliminates all temperature errors in typical industrial applications.",
     "option_D": "It is required by law only, depending on specific system requirements.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.5, "D": 1.3},
     "subtopic": "cold-junction",
     "explanation": "Thermocouple EMF reflects the difference between hot and reference junctions; reference temperature must be known for accurate hot-junction measurement."},
    {"question_id": "T11Q9", "topic": "Temperature sensors", "inherent_difficulty": 9.8,
     "question": "A resistive temperature detector (RTD) typically has better accuracy than a thermistor because:",
     "option_A": "It is always cheaper, depending on specific system requirements.",
     "option_B": "It requires no calibration under standard operating conditions.",
     "option_C": "It works only in laboratories in typical industrial applications.",
     "option_D": "Its resistance change is linear and reproducible across a wide range.",
     "answer": "D", "distractor_strength": {"A": 1.4, "B": 1.3, "C": 1.5},
     "subtopic": "RTD accuracy",
     "explanation": "RTD's linear, stable R-T relationship gives better accuracy than thermistor's nonlinear, variable curve."},
    {"question_id": "T12Q1", "topic": "Strain gauges", "inherent_difficulty": 1.0,
     "question": "The gauge factor of a strain gauge relates:",
     "option_A": "Voltage to current during normal system operation.",
     "option_B": "Fractional change in resistance to applied strain.",
     "option_C": "Temperature to length in practical implementations.",
     "option_D": "Frequency to time for most standard configurations.",
     "answer": "B", "distractor_strength": {"A": 1.5, "C": 1.6, "D": 1.2},
     "subtopic": "gauge factor",
     "explanation": "GF = (dR/R) / strain; it quantifies resistance sensitivity to strain."},
    {"question_id": "T12Q10", "topic": "Strain gauges", "inherent_difficulty": 1.6,
     "question": "Transverse sensitivity of a strain gauge refers to:",
     "option_A": "Its frequency response during normal system operation.",
     "option_B": "Its sensitivity to temperature changes only.",
     "option_C": "Its response to strain perpendicular to the main axis.",
     "option_D": "Its output impedance for most standard configurations.",
     "answer": "C", "distractor_strength": {"A": 1.5, "B": 1.4, "D": 1.3},
     "subtopic": "transverse response",
     "explanation": "Real gauges respond slightly to perpendicular strain; transverse sensitivity is typically 1-2% of axial."},
    {"question_id": "T12Q11", "topic": "Strain gauges", "inherent_difficulty": 2.3,
     "question": "Creep in a strain gauge bonding adhesive refers to:",
     "option_A": "Rapid failure of the gauge, depending on specific system requirements.",
     "option_B": "Instantaneous response to loading under standard operating conditions.",
     "option_C": "Gradual output drift under constant strain due to adhesive relaxation.",
     "option_D": "Elimination of all errors in typical industrial applications.",
     "answer": "C", "distractor_strength": {"A": 1.4, "B": 1.5, "D": 1.3},
     "subtopic": "adhesive creep",
     "explanation": "Over time, adhesive molecules relax slightly, causing apparent strain drift even though actual strain is constant."},
    {"question_id": "T12Q12", "topic": "Strain gauges", "inherent_difficulty": 2.9,
     "question": "A three-element strain gauge rosette (0\u00b0, 45\u00b0, 90\u00b0) is used to:",
     "option_A": "Measure only one strain direction, depending on specific system requirements.",
     "option_B": "Determine the complete 2D strain state (two principal strains and their orientation).",
     "option_C": "Measure temperature only under standard operating conditions and under typical loads.",
     "option_D": "Eliminate all calibration requirements in typical industrial applications.",
     "answer": "B", "distractor_strength": {"A": 1.5, "C": 1.4, "D": 1.3},
     "subtopic": "rosette analysis",
     "explanation": "Three strain measurements at known angles allow reconstruction of the full plane strain tensor."},
    {"question_id": "T12Q13", "topic": "Strain gauges", "inherent_difficulty": 3.5,
     "question": "Non-linearity in strain gauge output at high strain levels (>5000 microstrain) is primarily caused by:",
     "option_A": "The bridge circuit malfunction, depending on specific system requirements.",
     "option_B": "Deterioration of the wiring under standard operating conditions and within the system.",
     "option_C": "Temperature effects only in typical industrial applications and under typical loads.",
     "option_D": "Changes in gauge material properties and deviation from Hooke's law at high strain.",
     "answer": "D", "distractor_strength": {"A": 1.4, "B": 1.3, "C": 1.5},
     "subtopic": "high-strain nonlinearity",
     "explanation": "At large strains the material deviates from linear R-strain relationship; plastic deformation and material change occur."},
    {"question_id": "T12Q14", "topic": "Strain gauges", "inherent_difficulty": 4.1,
     "question": "Lead-wire resistance in a strain gauge measurement can be minimized by:",
     "option_A": "Using very thin wires to save material under specified design limits.",
     "option_B": "Using thick, short leads and compensating their effect in the bridge.",
     "option_C": "Placing the gauge kilometers away in typical industrial applications.",
     "option_D": "Removing all leads from the gauge under standard operating conditions.",
     "answer": "B", "distractor_strength": {"A": 1.5, "C": 1.4, "D": 1.6},
     "subtopic": "lead compensation",
     "explanation": "Large lead resistances create errors; they're minimized by using short, thick leads and bridge compensation techniques."},
    {"question_id": "T12Q15", "topic": "Strain gauges", "inherent_difficulty": 4.8,
     "question": "A strain gauge measurement system uses dual half-bridges (active and dummy) to achieve:",
     "option_A": "Halved sensitivity compared to a single gauge under typical loads.",
     "option_B": "Perfect temperature cancellation and increased output sensitivity.",
     "option_C": "Lower power consumption only under standard operating conditions.",
     "option_D": "Elimination of the need for calibration in practical scenarios.",
     "answer": "B", "distractor_strength": {"A": 1.5, "C": 1.4, "D": 1.3},
     "subtopic": "dual half-bridge",
     "explanation": "Active gauge responds to strain; dummy responds to temperature only. Combined output cancels thermal error and doubles sensitivity."},
    {"question_id": "T12Q2", "topic": "Strain gauges", "inherent_difficulty": 5.4,
     "question": "A strain gauge of 120 ohm and gauge factor 2.0 experiences 1000 microstrain. The change in resistance is about:",
     "option_A": "0.024 ohm.",
     "option_B": "24 ohm.",
     "option_C": "2.4 ohm.",
     "option_D": "0.24 ohm.",
     "answer": "D", "distractor_strength": {"A": 2.0, "B": 1.2, "C": 2.4},
     "subtopic": "resistance change",
     "explanation": "dR = GF x strain x R = 2.0 x 0.001 x 120 = 0.24 ohm."},
    {"question_id": "T12Q3", "topic": "Strain gauges", "inherent_difficulty": 6.0,
     "question": "In a quarter-bridge strain-gauge circuit, a dummy (inactive) gauge mounted on an unstrained sample of the same material is used mainly to:",
     "option_A": "Increase the gauge factor.",
     "option_B": "Provide temperature compensation.",
     "option_C": "Double the output sensitivity.",
     "option_D": "Convert AC to DC within the system.",
     "answer": "B", "distractor_strength": {"A": 1.7, "C": 2.3, "D": 1.4},
     "subtopic": "temperature compensation",
     "explanation": "The dummy gauge sees the same temperature but no strain, so thermal resistance changes cancel in the bridge."},
    {"question_id": "T12Q4", "topic": "Strain gauges", "inherent_difficulty": 6.7,
     "question": "A full (four-active-gauge) bridge on a bending beam, arranged with two gauges in tension and two in compression, gives an output that is, relative to a single active gauge:",
     "option_A": "One-quarter as large under standard operating conditions.",
     "option_B": "Four times as large and inherently temperature compensated.",
     "option_C": "Equal, depending on specific system requirements.",
     "option_D": "Zero in typical industrial applications and within the system.",
     "answer": "B", "distractor_strength": {"A": 1.8, "C": 1.9, "D": 2.0},
     "subtopic": "full bridge",
     "explanation": "Four active arms with the correct tension/compression placement add their contributions (x4 sensitivity) and cancel common-mode temperature effects."},
    {"question_id": "T12Q5", "topic": "Strain gauges", "inherent_difficulty": 7.3,
     "question": "What physical phenomenon does a strain gauge measure directly?",
     "option_A": "Temperature only under standard operating conditions.",
     "option_B": "Magnetic fields only for most standard configurations.",
     "option_C": "Light intensity in typical industrial applications.",
     "option_D": "Mechanical deformation (strain) via resistance change.",
     "answer": "D", "distractor_strength": {"A": 1.4, "B": 1.3, "C": 1.5},
     "subtopic": "strain measurement",
     "explanation": "Strain causes the gauge wire to stretch/compress, changing its resistance proportionally."},
    {"question_id": "T12Q6", "topic": "Strain gauges", "inherent_difficulty": 7.9,
     "question": "The typical gauge factor for a metal foil strain gauge is approximately:",
     "option_A": "0.5 to 1.0.",
     "option_B": "1.8 to 2.2.",
     "option_C": "5 to 10.",
     "option_D": "50 to 100.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.5, "D": 1.6},
     "subtopic": "typical GF",
     "explanation": "Metal foil gauges have GF \u2248 2.0; semiconductor gauges can have GF >> 100."},
    {"question_id": "T12Q7", "topic": "Strain gauges", "inherent_difficulty": 8.5,
     "question": "A half-bridge strain gauge configuration uses:",
     "option_A": "One active gauge and three equal resistors.",
     "option_B": "Only passive resistors during normal system operation.",
     "option_C": "One or two active gauges with compensators or dummies.",
     "option_D": "No bridge at all under standard operating conditions.",
     "answer": "C", "distractor_strength": {"A": 1.5, "B": 1.4, "D": 1.6},
     "subtopic": "half-bridge",
     "explanation": "Half-bridge uses active and dummy/compensator gauges to balance temperature effects and improve sensitivity."},
    {"question_id": "T12Q8", "topic": "Strain gauges", "inherent_difficulty": 9.2,
     "question": "Poisson's ratio (\u03bd) in strain measurement describes the relationship between:",
     "option_A": "Voltage and current for most standard configurations.",
     "option_B": "Stress and temperature only in practical scenarios.",
     "option_C": "Longitudinal and transverse strain under axial load.",
     "option_D": "Time constants under standard operating conditions.",
     "answer": "C", "distractor_strength": {"A": 1.4, "B": 1.5, "D": 1.3},
     "subtopic": "Poisson's effect",
     "explanation": "Poisson's ratio \u03bd relates perpendicular strains: \u03b5transverse = -\u03bd \u00d7 \u03b5axial."},
    {"question_id": "T12Q9", "topic": "Strain gauges", "inherent_difficulty": 9.8,
     "question": "The Wheatstone bridge output voltage for a single active gauge with bridge supply V is:",
     "option_A": "V \u00d7 (GF \u00d7 strain) / 2.",
     "option_B": "V \u00d7 GF \u00d7 strain.",
     "option_C": "V \u00d7 strain only.",
     "option_D": "Zero always.",
     "answer": "A", "distractor_strength": {"B": 1.5, "C": 1.6, "D": 1.4},
     "subtopic": "bridge voltage",
     "explanation": "For a quarter-bridge Vout = (Vex \u00d7 GF \u00d7 \u03b5) / 2; for half and full bridges the sensitivity improves."},
    {"question_id": "T13Q1", "topic": "Sensor errors and calibration", "inherent_difficulty": 1.0,
     "question": "Calibration of a sensor is the process of:",
     "option_A": "Permanently increasing its sensitivity, depending on specific system requirements and within the system.",
     "option_B": "Comparing its output against a known reference standard and adjusting/recording the relationship.",
     "option_C": "Replacing it with a digital one under standard operating conditions and in practical scenarios.",
     "option_D": "Removing all noise from the signal in typical industrial applications and in standard practice.",
     "answer": "B", "distractor_strength": {"A": 1.6, "C": 1.3, "D": 1.7},
     "subtopic": "calibration",
     "explanation": "Calibration establishes the input-output relationship by comparison with a traceable standard."},
    {"question_id": "T13Q10", "topic": "Sensor errors and calibration", "inherent_difficulty": 1.6,
     "question": "Environmental compensation in calibration accounts for effects of:",
     "option_A": "The operator's mood, depending on specific system requirements and within the system.",
     "option_B": "Only the sensor color under standard operating conditions and under typical loads.",
     "option_C": "Temperature, pressure, humidity and other ambient factors on sensor response.",
     "option_D": "No corrections needed in typical industrial applications and in standard practice.",
     "answer": "C", "distractor_strength": {"A": 1.4, "B": 1.3, "D": 1.2},
     "subtopic": "environmental effects",
     "explanation": "Environmental sensitivity is compensated by measuring conditions and applying correction factors to measurements."},
    {"question_id": "T13Q11", "topic": "Sensor errors and calibration", "inherent_difficulty": 2.3,
     "question": "The 'dead band' (or 'dead zone') of a sensor is the range of input where:",
     "option_A": "The output equals the input across the entire operating range.",
     "option_B": "Maximum sensitivity occurs in typical industrial applications.",
     "option_C": "The sensor becomes very accurate in practical implementations.",
     "option_D": "No output change is detected (insensitive region around zero).",
     "answer": "D", "distractor_strength": {"A": 1.3, "B": 1.5, "C": 1.4},
     "subtopic": "dead band",
     "explanation": "Dead band is an insensitive region where input changes produce negligible output changes."},
    {"question_id": "T13Q12", "topic": "Sensor errors and calibration", "inherent_difficulty": 2.9,
     "question": "A two-point calibration of a sensor is sufficient when:",
     "option_A": "Only two measurements are required.",
     "option_B": "The sensor response is linear.",
     "option_C": "The sensor is digital within the system.",
     "option_D": "No errors are possible.",
     "answer": "B", "distractor_strength": {"A": 1.5, "C": 1.4, "D": 1.3},
     "subtopic": "two-point calibration",
     "explanation": "For linear sensors, two points determine zero and span; nonlinear sensors need multi-point calibration."},
    {"question_id": "T13Q13", "topic": "Sensor errors and calibration", "inherent_difficulty": 3.5,
     "question": "Static calibration determines the sensor's:",
     "option_A": "Response to time-varying (dynamic) signals only.",
     "option_B": "Frequency response, depending on specific system requirements.",
     "option_C": "Relationship between constant input and steady-state output.",
     "option_D": "Color and size under standard operating conditions.",
     "answer": "C", "distractor_strength": {"A": 1.5, "B": 1.4, "D": 1.3},
     "subtopic": "static calibration",
     "explanation": "Static calibration uses DC or constant inputs to determine the DC transfer function (gain, offset, linearity)."},
    {"question_id": "T13Q14", "topic": "Sensor errors and calibration", "inherent_difficulty": 4.1,
     "question": "Monte Carlo uncertainty analysis in sensor measurement works by:",
     "option_A": "Using only worst-case errors addively, depending on specific system requirements and within the system.",
     "option_B": "Assuming errors always cancel perfectly under standard operating conditions and under typical loads.",
     "option_C": "Randomly sampling error distributions and simulating many outcomes to estimate total uncertainty.",
     "option_D": "Ignoring uncertainty entirely in typical industrial applications and in practical implementations.",
     "answer": "C", "distractor_strength": {"A": 1.5, "B": 1.4, "D": 1.3},
     "subtopic": "Monte Carlo",
     "explanation": "Monte Carlo simulation accounts for error correlations and probability distributions realistically."},
    {"question_id": "T13Q15", "topic": "Sensor errors and calibration", "inherent_difficulty": 4.8,
     "question": "A calibration certificate stating \u00b12% accuracy means:",
     "option_A": "The sensor is always exactly 2% off, depending on specific system requirements and within the system.",
     "option_B": "All errors are eliminated under standard operating conditions and in practical implementations.",
     "option_C": "Under the calibration conditions, 68% of measurements (1 sigma) are within \u00b12% of true value.",
     "option_D": "Only the maximum range is \u00b12% in typical industrial applications and in practical scenarios.",
     "answer": "C", "distractor_strength": {"A": 1.5, "B": 1.4, "D": 1.3},
     "subtopic": "accuracy statement",
     "explanation": "Accuracy statements typically give coverage at 1-sigma (68%) or 2-sigma (95%) confidence levels."},
    {"question_id": "T13Q2", "topic": "Sensor errors and calibration", "inherent_difficulty": 5.4,
     "question": "A measurement error that can be predicted and corrected (e.g. a constant offset) is classified as:",
     "option_A": "Random error.",
     "option_B": "Gross human blunder.",
     "option_C": "Systematic error.",
     "option_D": "Quantization error.",
     "answer": "C", "distractor_strength": {"A": 2.5, "B": 1.6, "D": 1.5},
     "subtopic": "systematic vs random",
     "explanation": "Systematic errors are repeatable and correctable; random errors scatter unpredictably about the mean."},
    {"question_id": "T13Q3", "topic": "Sensor errors and calibration", "inherent_difficulty": 6.0,
     "question": "'Traceability' of a calibration means that:",
     "option_A": "The sensor can be physically tracked by GPS, depending on specific system requirements and within the system.",
     "option_B": "The data file is saved on a server under standard operating conditions and in practical implementations.",
     "option_C": "The measurement is linked through an unbroken chain of comparisons to a national/international standard.",
     "option_D": "The error is always zero in typical industrial applications and across the entire operating range.",
     "answer": "C", "distractor_strength": {"A": 1.5, "B": 1.6, "D": 1.8},
     "subtopic": "traceability",
     "explanation": "Traceability requires an unbroken, documented chain of calibrations referencing recognised standards with stated uncertainties."},
    {"question_id": "T13Q4", "topic": "Sensor errors and calibration", "inherent_difficulty": 6.7,
     "question": "A sensor's best-fit straight line is found by least squares; the maximum deviation of actual data from this line, as a percentage of full-scale, is the:",
     "option_A": "Resolution in practical implementations.",
     "option_B": "Dead band in modern mechatronic systems.",
     "option_C": "Sensitivity under specified design limits.",
     "option_D": "Independent (best-fit) linearity error.",
     "answer": "D", "distractor_strength": {"A": 1.7, "B": 1.9, "C": 1.8},
     "subtopic": "linearity",
     "explanation": "Non-linearity is usually quoted as the worst deviation from the best-fit line expressed as a percentage of full-scale output."},
    {"question_id": "T13Q5", "topic": "Sensor errors and calibration", "inherent_difficulty": 7.3,
     "question": "What is the primary goal of sensor calibration?",
     "option_A": "To change its color, depending on specific system requirements.",
     "option_B": "To make the sensor heavier under standard operating conditions.",
     "option_C": "To establish the input-output relationship for accurate measurement.",
     "option_D": "To increase power consumption in typical industrial applications.",
     "answer": "C", "distractor_strength": {"A": 1.4, "B": 1.3, "D": 1.2},
     "subtopic": "calibration goal",
     "explanation": "Calibration quantifies the sensor's output response to known input values, enabling inverse mapping (output to input)."},
    {"question_id": "T13Q6", "topic": "Sensor errors and calibration", "inherent_difficulty": 7.9,
     "question": "A 'reference standard' used in calibration should ideally be:",
     "option_A": "Less accurate than the device being calibrated within the system.",
     "option_B": "The same accuracy as the device during normal system operation.",
     "option_C": "Several times more accurate (3-10x) than the device under test.",
     "option_D": "Has no accuracy requirement in typical industrial applications.",
     "answer": "C", "distractor_strength": {"A": 1.4, "B": 1.5, "D": 1.3},
     "subtopic": "standard hierarchy",
     "explanation": "Calibration standards must be superior (3-10x more accurate) to establish valid traceability."},
    {"question_id": "T13Q7", "topic": "Sensor errors and calibration", "inherent_difficulty": 8.5,
     "question": "Hysteresis error in a sensor is quantified as:",
     "option_A": "The maximum error when input increases only, depending on specific system requirements.",
     "option_B": "The time delay in response under standard operating conditions and within the system.",
     "option_C": "The maximum output difference for the same input approached from opposite directions.",
     "option_D": "The noise level in typical industrial applications and in modern mechatronic systems.",
     "answer": "C", "distractor_strength": {"A": 1.5, "B": 1.6, "D": 1.4},
     "subtopic": "hysteresis definition",
     "explanation": "Hysteresis is the maximum difference between forward and reverse traversal of the input-output characteristic."},
    {"question_id": "T13Q8", "topic": "Sensor errors and calibration", "inherent_difficulty": 9.2,
     "question": "A 'zero error' (also called 'bias error') affects a sensor measurement by:",
     "option_A": "Changing only high-range readings in practical implementations.",
     "option_B": "Occurring randomly, depending on specific system requirements.",
     "option_C": "Doubling the output under standard operating conditions.",
     "option_D": "Adding a constant offset to ALL readings at every input value.",
     "answer": "D", "distractor_strength": {"A": 1.5, "B": 1.6, "C": 1.4},
     "subtopic": "zero error",
     "explanation": "Zero error is a constant bias affecting the entire characteristic; it shifts the output-input curve without changing its slope."},
    {"question_id": "T13Q9", "topic": "Sensor errors and calibration", "inherent_difficulty": 9.8,
     "question": "A 'span error' (or 'sensitivity error') in a sensor differs from a zero error because:",
     "option_A": "Zero error affects only zero; span error affects only the maximum.",
     "option_B": "They are identical, depending on specific system requirements.",
     "option_C": "Span error changes the slope of the output-input characteristic.",
     "option_D": "Span error cannot be corrected in typical industrial applications.",
     "answer": "C", "distractor_strength": {"A": 1.5, "B": 1.4, "D": 1.3},
     "subtopic": "span error",
     "explanation": "Span error (sensitivity shift) changes the gain; zero error shifts the curve vertically without changing slope."},
    {"question_id": "T14Q1", "topic": "Filtering", "inherent_difficulty": 1.0,
     "question": "A low-pass filter is used in signal conditioning primarily to:",
     "option_A": "Pass low frequencies and attenuate high-frequency noise.",
     "option_B": "Pass only high frequencies in practical implementations.",
     "option_C": "Block DC entirely under standard operating conditions.",
     "option_D": "Convert analog to digital in modern mechatronic systems.",
     "answer": "A", "distractor_strength": {"B": 2.2, "C": 1.6, "D": 1.3},
     "subtopic": "low-pass",
     "explanation": "A low-pass filter passes signals below its cutoff and attenuates higher-frequency noise."},
    {"question_id": "T14Q10", "topic": "Filtering", "inherent_difficulty": 1.6,
     "question": "Phase shift in a filter response means:",
     "option_A": "Some frequency components are delayed relative to others.",
     "option_B": "The signal amplitude is changed in practical scenarios.",
     "option_C": "The signal is amplified for most standard configurations.",
     "option_D": "No change occurs, depending on specific system requirements.",
     "answer": "A", "distractor_strength": {"B": 1.5, "C": 1.4, "D": 1.3},
     "subtopic": "phase shift",
     "explanation": "Different frequencies experience different delays (group delay), distorting the time-domain waveform."},
    {"question_id": "T14Q11", "topic": "Filtering", "inherent_difficulty": 2.3,
     "question": "A passive filter is composed primarily of:",
     "option_A": "Diodes exclusively under standard operating conditions.",
     "option_B": "Only transistors in typical industrial applications.",
     "option_C": "Resistors, capacitors and inductors without amplifiers.",
     "option_D": "Batteries, depending on specific system requirements.",
     "answer": "C", "distractor_strength": {"A": 1.5, "B": 1.4, "D": 1.3},
     "subtopic": "passive filter",
     "explanation": "Passive filters use only L, C and R elements; they attenuate signals and have no gain."},
    {"question_id": "T14Q12", "topic": "Filtering", "inherent_difficulty": 2.9,
     "question": "An active filter can provide advantages over a passive filter, including:",
     "option_A": "No frequency dependence in practical implementations.",
     "option_B": "Gain, better impedance matching and steeper roll-off.",
     "option_C": "Perfect filtering with no ripple under typical loads.",
     "option_D": "No power consumption during normal system operation.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.5, "D": 1.3},
     "subtopic": "active filter",
     "explanation": "Active filters use op-amps to provide gain, buffer outputs, and implement complex transfer functions efficiently."},
    {"question_id": "T14Q13", "topic": "Filtering", "inherent_difficulty": 3.5,
     "question": "A notch filter (band-stop filter) is used to:",
     "option_A": "Pass all frequencies without any attenuation under standard operating conditions.",
     "option_B": "Provide deep attenuation at a specific frequency (e.g. 50/60 Hz mains interference).",
     "option_C": "Amplify the input signal, depending on specific system requirements and within the system.",
     "option_D": "Change the signal color in typical industrial applications and in standard practice.",
     "answer": "B", "distractor_strength": {"A": 1.5, "C": 1.4, "D": 1.3},
     "subtopic": "notch filter",
     "explanation": "Notch filters sharply reject a narrow frequency band while passing frequencies on either side."},
    {"question_id": "T14Q14", "topic": "Filtering", "inherent_difficulty": 4.1,
     "question": "The Nyquist frequency in sampling is:",
     "option_A": "The maximum frequency that must be present in the signal.",
     "option_B": "The cutoff frequency of the ADC in practical implementations.",
     "option_C": "Always 60 Hz, depending on specific system requirements.",
     "option_D": "Half the sampling rate; frequencies above this are aliased.",
     "answer": "D", "distractor_strength": {"A": 1.5, "B": 1.3, "C": 1.4},
     "subtopic": "Nyquist frequency",
     "explanation": "f_Nyquist = f_sample / 2; the anti-aliasing filter must remove all content above this frequency."},
    {"question_id": "T14Q15", "topic": "Filtering", "inherent_difficulty": 4.8,
     "question": "A digital filter differs from an analog filter in that:",
     "option_A": "It operates on sampled data in the time or frequency domain using arithmetic operations.",
     "option_B": "It uses only transistors, depending on specific system requirements and within the system.",
     "option_C": "It cannot be effective under standard operating conditions and in practical scenarios.",
     "option_D": "It has no filter characteristics in typical industrial applications and under typical loads.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.5, "D": 1.3},
     "subtopic": "digital filter",
     "explanation": "Digital filters process discrete-time samples via difference equations or FFT-based methods, enabling flexible, precise filtering."},
    {"question_id": "T14Q2", "topic": "Filtering", "inherent_difficulty": 5.4,
     "question": "A first-order RC low-pass filter has R = 1.6 kohm and C = 0.1 microF. Its approximate cutoff frequency is:",
     "option_A": "100 Hz.",
     "option_B": "10 kHz.",
     "option_C": "1 kHz.",
     "option_D": "16 kHz.",
     "answer": "C", "distractor_strength": {"A": 2.0, "B": 2.2, "D": 1.8},
     "subtopic": "RC cutoff",
     "explanation": "fc = 1/(2 pi R C) = 1/(2 pi x 1600 x 1e-7) approx 995 Hz approx 1 kHz."},
    {"question_id": "T14Q3", "topic": "Filtering", "inherent_difficulty": 6.0,
     "question": "An anti-aliasing filter must be placed:",
     "option_A": "Before the sampler/ADC, to remove components above half the sampling rate.",
     "option_B": "After the ADC, in software, depending on specific system requirements.",
     "option_C": "Inside the display unit under standard operating conditions and within the system.",
     "option_D": "Only on digital signals in typical industrial applications and under typical loads.",
     "answer": "A", "distractor_strength": {"B": 2.4, "C": 1.4, "D": 1.7},
     "subtopic": "anti-aliasing",
     "explanation": "Aliasing must be prevented before sampling, so an analog low-pass filter removes content above the Nyquist frequency ahead of the ADC."},
    {"question_id": "T14Q4", "topic": "Filtering", "inherent_difficulty": 6.7,
     "question": "A Butterworth filter is often chosen over a Chebyshev filter of the same order when the design priority is:",
     "option_A": "The sharpest possible roll-off regardless of ripple within the system.",
     "option_B": "A maximally flat passband (no ripple), accepting a gentler roll-off.",
     "option_C": "Linear phase only, depending on specific system requirements.",
     "option_D": "Minimum component count under standard operating conditions.",
     "answer": "B", "distractor_strength": {"A": 2.3, "C": 2.0, "D": 1.6},
     "subtopic": "filter approximations",
     "explanation": "Butterworth gives a maximally flat passband at the cost of a less steep transition; Chebyshev trades passband ripple for sharper roll-off."},
    {"question_id": "T14Q5", "topic": "Filtering", "inherent_difficulty": 7.3,
     "question": "What is the primary purpose of a filter in a measurement system?",
     "option_A": "To increase the sensor output, depending on specific system requirements.",
     "option_B": "To remove unwanted frequency components (noise) while preserving desired signal.",
     "option_C": "To convert analog to digital under standard operating conditions and within the system.",
     "option_D": "To amplify all frequencies equally in typical industrial applications.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.5, "D": 1.3},
     "subtopic": "filter purpose",
     "explanation": "Filters selectively pass or block frequencies to improve signal quality and reduce measurement error."},
    {"question_id": "T14Q6", "topic": "Filtering", "inherent_difficulty": 7.9,
     "question": "The 'cutoff frequency' (or '-3dB point') of a filter is where:",
     "option_A": "The output power drops to half the passband power.",
     "option_B": "The filter completely stops all signals.",
     "option_C": "The filter amplifies the signal within the system.",
     "option_D": "The phase shift is zero in practical scenarios.",
     "answer": "A", "distractor_strength": {"B": 1.5, "C": 1.4, "D": 1.3},
     "subtopic": "cutoff frequency",
     "explanation": "-3dB corresponds to 10 log(0.5) = -3.01 dB; output power is half at this frequency."},
    {"question_id": "T14Q7", "topic": "Filtering", "inherent_difficulty": 8.5,
     "question": "A high-pass filter allows frequencies:",
     "option_A": "Below its cutoff to pass; above to be blocked.",
     "option_B": "Above its cutoff to pass; below to be blocked.",
     "option_C": "At exactly the cutoff frequency only.",
     "option_D": "At all frequencies equally within the system.",
     "answer": "B", "distractor_strength": {"A": 1.6, "C": 1.5, "D": 1.4},
     "subtopic": "high-pass",
     "explanation": "High-pass filters remove DC and low-frequency components, passing only high frequencies."},
    {"question_id": "T14Q8", "topic": "Filtering", "inherent_difficulty": 9.2,
     "question": "A band-pass filter has two cutoff frequencies defining:",
     "option_A": "Only one passband, depending on specific system requirements.",
     "option_B": "A stopband only under standard operating conditions and within the system.",
     "option_C": "Only the lower frequency limit in typical industrial applications.",
     "option_D": "A passband between f_low and f_high; frequencies outside are attenuated.",
     "answer": "D", "distractor_strength": {"A": 1.5, "B": 1.4, "C": 1.6},
     "subtopic": "band-pass definition",
     "explanation": "Band-pass combines high-pass (f > f_low) and low-pass (f < f_high) actions to select a frequency window."},
    {"question_id": "T14Q9", "topic": "Filtering", "inherent_difficulty": 9.8,
     "question": "The 'roll-off rate' of a filter is specified in units of:",
     "option_A": "Hertz per input, depending on specific system requirements.",
     "option_B": "Decibels per decade (or octave) to characterize the filter steepness.",
     "option_C": "Volts per second under standard operating conditions and within the system.",
     "option_D": "Watts per Hz in typical industrial applications and under typical loads.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.5, "D": 1.3},
     "subtopic": "roll-off rate",
     "explanation": "A first-order filter rolls off at -20 dB/decade; second-order at -40 dB/decade, etc."},
    {"question_id": "T15Q1", "topic": "Operational amplifier signal conditioning", "inherent_difficulty": 1.0,
     "question": "A non-inverting amplifier with R1 (to ground) = 1 kohm and Rf = 9 kohm has a voltage gain of:",
     "option_A": "9.",
     "option_B": "10.",
     "option_C": "0.9.",
     "option_D": "-9.",
     "answer": "B", "distractor_strength": {"A": 2.5, "C": 1.5, "D": 1.6},
     "subtopic": "non-inverting gain",
     "explanation": "Gain = 1 + Rf/R1 = 1 + 9 = 10."},
    {"question_id": "T15Q10", "topic": "Operational amplifier signal conditioning", "inherent_difficulty": 1.6,
     "question": "An op-amp integrator (capacitive feedback) produces an output proportional to:",
     "option_A": "The integral (accumulated sum) of the input over time.",
     "option_B": "The derivative of the input in practical scenarios.",
     "option_C": "Only the constant DC value in practical implementations.",
     "option_D": "The input squared under standard operating conditions.",
     "answer": "A", "distractor_strength": {"B": 1.5, "C": 1.4, "D": 1.3},
     "subtopic": "integrator",
     "explanation": "V_out = -(1/RC) \u222b V_in dt; integrator performs the inverse of differentiation."},
    {"question_id": "T15Q11", "topic": "Operational amplifier signal conditioning", "inherent_difficulty": 2.3,
     "question": "An instrumentation amplifier is preferred for low-level sensor signals because it provides:",
     "option_A": "Only high gain, depending on specific system requirements and within the system.",
     "option_B": "Very high input impedance and high CMRR to reject noise from long sensor wires.",
     "option_C": "Direct digital output under standard operating conditions and under typical loads.",
     "option_D": "No gain at all in typical industrial applications and in practical scenarios.",
     "answer": "B", "distractor_strength": {"A": 1.5, "C": 1.4, "D": 1.3},
     "subtopic": "instrumentation amp",
     "explanation": "In-amp's input buffer stage has extreme high impedance and differential architecture gives excellent CMRR."},
    {"question_id": "T15Q12", "topic": "Operational amplifier signal conditioning", "inherent_difficulty": 2.9,
     "question": "An op-amp comparator (without feedback) is used to:",
     "option_A": "Amplify analog signals with adjustable gain in modern mechatronic systems.",
     "option_B": "Generate a sine wave, depending on specific system requirements.",
     "option_C": "Integrate the input signal under standard operating conditions.",
     "option_D": "Compare two inputs and output a digital HIGH/LOW based on which is larger.",
     "answer": "D", "distractor_strength": {"A": 1.5, "B": 1.3, "C": 1.4},
     "subtopic": "comparator",
     "explanation": "Comparators lack feedback; they output digital levels (saturated) depending on whether V+ > V- or vice versa."},
    {"question_id": "T15Q13", "topic": "Operational amplifier signal conditioning", "inherent_difficulty": 3.5,
     "question": "The offset voltage of a real op-amp is:",
     "option_A": "A small residual input voltage that produces non-zero output when inputs are shorted together.",
     "option_B": "Always zero for all op-amps, depending on specific system requirements and under typical loads.",
     "option_C": "The output impedance under standard operating conditions and for most standard configurations.",
     "option_D": "Only important for very large signals in typical industrial applications and within the system.",
     "answer": "A", "distractor_strength": {"B": 1.5, "C": 1.4, "D": 1.3},
     "subtopic": "offset voltage",
     "explanation": "Input offset voltage (typically 0.5-5 mV for general-purpose op-amps) is a manufacturing defect that must be compensated for accurate circuits."},
    {"question_id": "T15Q14", "topic": "Operational amplifier signal conditioning", "inherent_difficulty": 4.1,
     "question": "The slew rate of an op-amp is the maximum rate at which:",
     "option_A": "The power supply can be increased in practical scenarios.",
     "option_B": "The input impedance decreases in practical implementations.",
     "option_C": "The output voltage can change in response to an input step.",
     "option_D": "The frequency can be adjusted in modern mechatronic systems.",
     "answer": "C", "distractor_strength": {"A": 1.5, "B": 1.4, "D": 1.3},
     "subtopic": "slew rate",
     "explanation": "Slew rate (e.g. 0.5-13 V/\u00b5s) limits how fast output can change; exceeded slew causes distortion on fast signals."},
    {"question_id": "T15Q15", "topic": "Operational amplifier signal conditioning", "inherent_difficulty": 4.8,
     "question": "A precision log (logarithmic) amplifier using an op-amp can be used to:",
     "option_A": "Measure only large signals above 100V under standard operating conditions.",
     "option_B": "Eliminate all noise, depending on specific system requirements.",
     "option_C": "Amplify negative signals only in typical industrial applications.",
     "option_D": "Compress wide dynamic range (e.g. 1\u00b5V to 1V) into a narrower output range.",
     "answer": "D", "distractor_strength": {"A": 1.5, "B": 1.3, "C": 1.4},
     "subtopic": "log amplifier",
     "explanation": "Log amp using a diode in feedback (V_out = -ln(Vin/Vin_ref)) compresses wide input ranges into manageable outputs."},
    {"question_id": "T15Q2", "topic": "Operational amplifier signal conditioning", "inherent_difficulty": 5.4,
     "question": "A summing amplifier is used to:",
     "option_A": "Add several weighted input voltages into one output.",
     "option_B": "Integrate a single input in practical implementations.",
     "option_C": "Compare two inputs and output logic levels.",
     "option_D": "Filter high frequencies in modern mechatronic systems.",
     "answer": "A", "distractor_strength": {"B": 1.8, "C": 1.7, "D": 1.5},
     "subtopic": "summing amplifier",
     "explanation": "An inverting summing amplifier outputs -(Rf/R1 V1 + Rf/R2 V2 + ...), a weighted sum of inputs."},
    {"question_id": "T15Q3", "topic": "Operational amplifier signal conditioning", "inherent_difficulty": 6.0,
     "question": "A difference amplifier has a common-mode rejection ratio (CMRR) of 80 dB. With a 1 V common-mode input and a differential gain of 10, the common-mode error referred to the output is about:",
     "option_A": "0.1 mV.",
     "option_B": "100 mV.",
     "option_C": "10 mV.",
     "option_D": "1 mV.",
     "answer": "D", "distractor_strength": {"A": 2.0, "B": 1.7, "C": 2.3},
     "subtopic": "CMRR",
     "explanation": "80 dB -> CMRR = 10^4. Common-mode gain = Ad/CMRR = 10/1e4 = 1e-3, so 1 V common-mode gives 1 mV at the output."},
    {"question_id": "T15Q4", "topic": "Operational amplifier signal conditioning", "inherent_difficulty": 6.7,
     "question": "When conditioning a low-level thermocouple signal, op-amp input bias current causes the worst offset drift error when the source resistance is:",
     "option_A": "Very low and balanced on both inputs.",
     "option_B": "High and unbalanced between the two inputs.",
     "option_C": "Exactly zero under specified design limits.",
     "option_D": "Purely capacitive in practical scenarios.",
     "answer": "B", "distractor_strength": {"A": 2.2, "C": 1.7, "D": 2.0},
     "subtopic": "bias-current error",
     "explanation": "Bias current flowing through unequal source resistances creates a differential offset voltage; matching source resistances (and low values) minimises it."},
    {"question_id": "T15Q5", "topic": "Operational amplifier signal conditioning", "inherent_difficulty": 7.3,
     "question": "What is the main function of an op-amp in signal conditioning?",
     "option_A": "To display the measurement, depending on specific system requirements.",
     "option_B": "To replace the sensor completely under standard operating conditions.",
     "option_C": "To generate electrical power in typical industrial applications.",
     "option_D": "To amplify, filter and condition analog sensor signals for processing.",
     "answer": "D", "distractor_strength": {"A": 1.3, "B": 1.4, "C": 1.5},
     "subtopic": "op-amp role",
     "explanation": "Op-amps provide gain, filtering, impedance transformation and protection between sensors and data acquisition systems."},
    {"question_id": "T15Q6", "topic": "Operational amplifier signal conditioning", "inherent_difficulty": 7.9,
     "question": "An inverting amplifier configuration produces an output that is:",
     "option_A": "In-phase with the input in standard practice.",
     "option_B": "Unaffected by the input under typical loads.",
     "option_C": "Always positive in practical implementations.",
     "option_D": "Phase-inverted (180\u00b0 opposite) and amplified.",
     "answer": "D", "distractor_strength": {"A": 1.5, "B": 1.3, "C": 1.4},
     "subtopic": "inverting config",
     "explanation": "The inverting input causes output V_out = -(Rf/Rin) \u00d7 V_in; gain and 180\u00b0 phase shift."},
    {"question_id": "T15Q7", "topic": "Operational amplifier signal conditioning", "inherent_difficulty": 8.5,
     "question": "The gain of an inverting amplifier is determined by:",
     "option_A": "The ratio of feedback resistor to input resistor: Gain = -Rf/Rin.",
     "option_B": "Only the op-amp open-loop gain across the entire operating range.",
     "option_C": "The power supply voltage, depending on specific system requirements.",
     "option_D": "The ambient temperature only under standard operating conditions.",
     "answer": "A", "distractor_strength": {"B": 1.5, "C": 1.4, "D": 1.3},
     "subtopic": "inverting gain",
     "explanation": "Negative feedback forces the gain to depend on passive components (Rf, Rin), independent of op-amp characteristics."},
    {"question_id": "T15Q8", "topic": "Operational amplifier signal conditioning", "inherent_difficulty": 9.2,
     "question": "A voltage follower (unity-gain buffer) is used primarily to:",
     "option_A": "Amplify signals to high levels under standard operating conditions.",
     "option_B": "Filter high-frequency noise, depending on specific system requirements.",
     "option_C": "Provide high input impedance while maintaining the input signal level.",
     "option_D": "Invert the input signal in typical industrial applications.",
     "answer": "C", "distractor_strength": {"A": 1.5, "B": 1.4, "D": 1.3},
     "subtopic": "voltage follower",
     "explanation": "A follower (Vout = Vin, gain = 1) has very high input impedance, effectively isolating the source from loading."},
    {"question_id": "T15Q9", "topic": "Operational amplifier signal conditioning", "inherent_difficulty": 9.8,
     "question": "Common-mode rejection ratio (CMRR) measures an op-amp's ability to:",
     "option_A": "Ignore signals common to both inputs while amplifying differential signals.",
     "option_B": "Generate high output voltage, depending on specific system requirements.",
     "option_C": "Reject all frequencies under standard operating conditions and within the system.",
     "option_D": "Amplify DC only in typical industrial applications and under typical loads.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.5, "D": 1.3},
     "subtopic": "CMRR definition",
     "explanation": "CMRR = differential gain / common-mode gain; high CMRR rejects noise common to both inputs."},
    {"question_id": "T16Q1", "topic": "Analog-to-digital conversion", "inherent_difficulty": 1.0,
     "question": "The resolution of an n-bit ADC is the number of output codes, equal to:",
     "option_A": "n.",
     "option_B": "2n.",
     "option_C": "2^n.",
     "option_D": "n^2.",
     "answer": "C", "distractor_strength": {"A": 1.5, "B": 2.2, "D": 1.6},
     "subtopic": "resolution",
     "explanation": "An n-bit converter has 2^n distinct output levels."},
    {"question_id": "T16Q10", "topic": "Analog-to-digital conversion", "inherent_difficulty": 1.6,
     "question": "A 'flash' ADC architecture is characterized by:",
     "option_A": "Slowest possible conversion, depending on specific system requirements.",
     "option_B": "No digital output under standard operating conditions and under typical loads.",
     "option_C": "Sequential sampling only in typical industrial applications and within the system.",
     "option_D": "Parallel comparators for every level; extremely fast but uses more area/power.",
     "answer": "D", "distractor_strength": {"A": 1.5, "B": 1.3, "C": 1.4},
     "subtopic": "flash ADC",
     "explanation": "Flash converters use 2^n - 1 comparators for instant conversion (nanoseconds); ideal for video/radar."},
    {"question_id": "T16Q11", "topic": "Analog-to-digital conversion", "inherent_difficulty": 2.3,
     "question": "A successive-approximation ADC works by:",
     "option_A": "Using all comparators simultaneously in modern mechatronic systems.",
     "option_B": "Storing all data on disk, depending on specific system requirements.",
     "option_C": "Measuring signal frequency only in typical industrial applications.",
     "option_D": "Trying binary patterns sequentially to narrow down the input value.",
     "answer": "D", "distractor_strength": {"A": 1.5, "B": 1.3, "C": 1.4},
     "subtopic": "SAR ADC",
     "explanation": "SAR tests each bit position (MSB to LSB) with a single comparator, giving moderate speed and area."},
    {"question_id": "T16Q12", "topic": "Analog-to-digital conversion", "inherent_difficulty": 2.9,
     "question": "The 'dynamic range' of an ADC is:",
     "option_A": "Only the maximum voltage it can measure, depending on specific system requirements.",
     "option_B": "The power consumption under standard operating conditions and in practical implementations.",
     "option_C": "The speed of conversion only in typical industrial applications and in practical scenarios.",
     "option_D": "The ratio of the maximum to the minimum detectable signal (e.g. 6.02n + SNR dB for n bits).",
     "answer": "D", "distractor_strength": {"A": 1.5, "B": 1.3, "C": 1.4},
     "subtopic": "dynamic range",
     "explanation": "Dynamic range = 20 log(Vmax/Vmin); more bits increase dynamic range by ~6 dB per bit."},
    {"question_id": "T16Q13", "topic": "Analog-to-digital conversion", "inherent_difficulty": 3.5,
     "question": "Differential nonlinearity (DNL) of an ADC describes:",
     "option_A": "The average gain across the range in practical scenarios.",
     "option_B": "The sampling rate only in typical industrial applications.",
     "option_C": "The total output voltage range in practical implementations.",
     "option_D": "The variation in step size (1 LSB) between adjacent codes.",
     "answer": "D", "distractor_strength": {"A": 1.5, "B": 1.3, "C": 1.4},
     "subtopic": "DNL",
     "explanation": "DNL < 1 LSB ensures monotonicity; if DNL = 1 LSB a code may be missing."},
    {"question_id": "T16Q14", "topic": "Analog-to-digital conversion", "inherent_difficulty": 4.1,
     "question": "Integral nonlinearity (INL) of an ADC is the:",
     "option_A": "Only the output noise level, depending on specific system requirements.",
     "option_B": "Deviation of the actual transfer curve from the ideal straight line.",
     "option_C": "Time delay in conversion under standard operating conditions.",
     "option_D": "Power dissipation only in typical industrial applications.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.5, "D": 1.3},
     "subtopic": "INL",
     "explanation": "INL accumulates DNL errors; it represents the worst-case deviation from ideal transfer function."},
    {"question_id": "T16Q15", "topic": "Analog-to-digital conversion", "inherent_difficulty": 4.8,
     "question": "For an ADC system with f_sample = 10 kHz, the anti-aliasing filter must attenuate signals above:",
     "option_A": "1 kHz under typical loads.",
     "option_B": "10 kHz within the system.",
     "option_C": "5 kHz (Nyquist frequency).",
     "option_D": "20 kHz in standard practice.",
     "answer": "C", "distractor_strength": {"A": 1.5, "B": 1.6, "D": 1.4},
     "subtopic": "Nyquist filter",
     "explanation": "Anti-aliasing filter cutoff \u2264 fs/2 = 5 kHz for 10 kHz sampling to prevent aliasing."},
    {"question_id": "T16Q2", "topic": "Analog-to-digital conversion", "inherent_difficulty": 5.4,
     "question": "A 10-bit ADC has a full-scale input range of 0 to 5 V. Its quantization step (1 LSB) is about:",
     "option_A": "5 mV.",
     "option_B": "0.5 V.",
     "option_C": "4.9 mV.",
     "option_D": "49 mV.",
     "answer": "C", "distractor_strength": {"A": 2.3, "B": 1.6, "D": 2.0},
     "subtopic": "LSB size",
     "explanation": "1 LSB = 5 V / 2^10 = 5/1024 approx 4.88 mV."},
    {"question_id": "T16Q3", "topic": "Analog-to-digital conversion", "inherent_difficulty": 6.0,
     "question": "Compared with a successive-approximation ADC, a dual-slope (integrating) ADC is generally:",
     "option_A": "Much faster but noisier across the entire operating range.",
     "option_B": "Only usable for digital inputs in practical implementations.",
     "option_C": "Slower but offers excellent noise rejection and linearity.",
     "option_D": "Incapable of high resolution under specified design limits.",
     "answer": "C", "distractor_strength": {"A": 2.2, "B": 1.4, "D": 1.8},
     "subtopic": "ADC architectures",
     "explanation": "Dual-slope converters integrate the input, averaging out noise (and rejecting mains hum if timed to it), at the cost of conversion speed."},
    {"question_id": "T16Q4", "topic": "Analog-to-digital conversion", "inherent_difficulty": 6.7,
     "question": "The Shannon-Nyquist sampling theorem requires that to reconstruct a signal of maximum frequency fmax, the sampling rate fs must satisfy:",
     "option_A": "fs > fmax.",
     "option_B": "fs = fmax/2.",
     "option_C": "fs > 2 fmax.",
     "option_D": "fs > fmax/2.",
     "answer": "C", "distractor_strength": {"A": 2.3, "B": 1.7, "D": 2.0},
     "subtopic": "sampling theorem",
     "explanation": "Sampling must exceed twice the highest signal frequency to avoid aliasing and allow exact reconstruction."},
    {"question_id": "T16Q5", "topic": "Analog-to-digital conversion", "inherent_difficulty": 7.3,
     "question": "An ADC's primary function is to:",
     "option_A": "Convert analog voltage signals into digital codes for processing.",
     "option_B": "Amplify the signal to high levels during normal system operation.",
     "option_C": "Generate analog signals from digital inputs in standard practice.",
     "option_D": "Display the measurement on a screen in practical implementations.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.5, "D": 1.3},
     "subtopic": "ADC purpose",
     "explanation": "ADC samples and quantizes analog signals, producing discrete digital output codes."},
    {"question_id": "T16Q6", "topic": "Analog-to-digital conversion", "inherent_difficulty": 7.9,
     "question": "An 8-bit ADC has how many possible output codes?",
     "option_A": "8.",
     "option_B": "16.",
     "option_C": "256.",
     "option_D": "128.",
     "answer": "C", "distractor_strength": {"A": 1.4, "B": 1.5, "D": 1.6},
     "subtopic": "bit resolution",
     "explanation": "2^8 = 256 distinct output levels for an 8-bit converter."},
    {"question_id": "T16Q7", "topic": "Analog-to-digital conversion", "inherent_difficulty": 8.5,
     "question": "'Quantization error' in an ADC is caused by:",
     "option_A": "The lack of a power supply for most standard configurations.",
     "option_B": "Electrical noise in the circuit in practical implementations.",
     "option_C": "Temperature variations only during normal system operation.",
     "option_D": "The continuous input being mapped to discrete output levels.",
     "answer": "D", "distractor_strength": {"A": 1.3, "B": 1.5, "C": 1.4},
     "subtopic": "quantization",
     "explanation": "Quantization error = \u00b11/2 LSB (half the step size) due to rounding the input to the nearest level."},
    {"question_id": "T16Q8", "topic": "Analog-to-digital conversion", "inherent_difficulty": 9.2,
     "question": "The 'conversion time' of an ADC is:",
     "option_A": "Always zero for perfect conversion, depending on specific system requirements.",
     "option_B": "Independent of the number of bits under standard operating conditions and within the system.",
     "option_C": "The time required to complete one analog-to-digital conversion (sample to digital output).",
     "option_D": "The time to power up the device in typical industrial applications and under typical loads.",
     "answer": "C", "distractor_strength": {"A": 1.4, "B": 1.5, "D": 1.3},
     "subtopic": "conversion time",
     "explanation": "Conversion time ranges from nanoseconds (flash ADC) to milliseconds (integrating ADC)."},
    {"question_id": "T16Q9", "topic": "Analog-to-digital conversion", "inherent_difficulty": 9.8,
     "question": "Aliasing in digital sampling occurs when:",
     "option_A": "The signal is too strong, depending on specific system requirements and within the system.",
     "option_B": "Signal components above the Nyquist frequency fold back and appear as lower frequencies.",
     "option_C": "The ADC has too many bits under standard operating conditions and in standard practice.",
     "option_D": "Noise is completely eliminated in typical industrial applications and under typical loads.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.5, "D": 1.3},
     "subtopic": "aliasing",
     "explanation": "Frequencies above fs/2 appear as lower frequencies in sampled data, corrupting the reconstruction."},
    {"question_id": "T17Q1", "topic": "Flip-flops and registers", "inherent_difficulty": 1.0,
     "question": "A flip-flop is a digital circuit element that:",
     "option_A": "Stores one bit of information.",
     "option_B": "Adds two binary numbers.",
     "option_C": "Converts analog to digital.",
     "option_D": "Amplifies voltage.",
     "answer": "A", "distractor_strength": {"B": 1.6, "C": 1.5, "D": 1.3},
     "subtopic": "flip-flop basics",
     "explanation": "A bistable flip-flop holds one bit until clocked/changed - the basic memory cell."},
    {"question_id": "T17Q10", "topic": "Flip-flops and registers", "inherent_difficulty": 1.6,
     "question": "An 'asynchronous' (ripple) counter has:",
     "option_A": "Each flip-flop clocked by the output of the previous one (cascaded).",
     "option_B": "All flip-flops clocked simultaneously in modern mechatronic systems.",
     "option_C": "No clock input at all, depending on specific system requirements.",
     "option_D": "No counting capability under standard operating conditions.",
     "answer": "A", "distractor_strength": {"B": 1.5, "C": 1.4, "D": 1.3},
     "subtopic": "ripple counter",
     "explanation": "Ripple (asynchronous) counters are simple but slow due to propagation delay accumulation."},
    {"question_id": "T17Q11", "topic": "Flip-flops and registers", "inherent_difficulty": 2.3,
     "question": "The advantage of a synchronous counter over a ripple counter is:",
     "option_A": "All flip-flops are clocked together, eliminating propagation delay and glitches.",
     "option_B": "It costs less money, depending on specific system requirements and within the system.",
     "option_C": "It cannot count under standard operating conditions and in practical scenarios.",
     "option_D": "It requires no clock in typical industrial applications and under typical loads.",
     "answer": "A", "distractor_strength": {"B": 1.5, "C": 1.4, "D": 1.3},
     "subtopic": "synchronous counter",
     "explanation": "Synchronous counters clock all stages together, enabling high-speed operation without transient invalid states."},
    {"question_id": "T17Q12", "topic": "Flip-flops and registers", "inherent_difficulty": 2.9,
     "question": "A parallel-in/serial-out (PISO) shift register is used to:",
     "option_A": "Load multiple bits in parallel and shift them out serially one bit at a time.",
     "option_B": "Only receive serial input, depending on specific system requirements.",
     "option_C": "Generate random numbers under standard operating conditions and within the system.",
     "option_D": "Amplify digital signals in typical industrial applications and under typical loads.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.5, "D": 1.3},
     "subtopic": "PISO",
     "explanation": "PISO converters transform parallel data into a serial bitstream for transmission or interfacing."},
    {"question_id": "T17Q13", "topic": "Flip-flops and registers", "inherent_difficulty": 3.5,
     "question": "In an edge-triggered flip-flop, data is sampled and stored:",
     "option_A": "Only at the rising (or falling) clock edge.",
     "option_B": "Continuously at all times within the system.",
     "option_C": "When power is removed in standard practice.",
     "option_D": "Randomly without any clock under typical loads.",
     "answer": "A", "distractor_strength": {"B": 1.5, "C": 1.4, "D": 1.3},
     "subtopic": "edge trigger",
     "explanation": "Edge-triggered design enables synchronous, predictable operation in clocked systems."},
    {"question_id": "T17Q14", "topic": "Flip-flops and registers", "inherent_difficulty": 4.1,
     "question": "A preset (or set) input on a flip-flop is used to:",
     "option_A": "Slow down the clock, depending on specific system requirements.",
     "option_B": "Force the output Q to 1 asynchronously (independent of clock).",
     "option_C": "Change the flip-flop type under standard operating conditions.",
     "option_D": "Eliminate the need for clocking under specified design limits.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.5, "D": 1.3},
     "subtopic": "preset input",
     "explanation": "Asynchronous preset/clear inputs allow immediate state initialization without waiting for a clock pulse."},
    {"question_id": "T17Q15", "topic": "Flip-flops and registers", "inherent_difficulty": 4.8,
     "question": "In a circular (ring) shift register, after one complete cycle of shifting, the pattern:",
     "option_A": "Is permanently lost, depending on specific system requirements.",
     "option_B": "Becomes all zeros under standard operating conditions.",
     "option_C": "Returns to its original state (data cycles through the register).",
     "option_D": "Inverts completely in typical industrial applications.",
     "answer": "C", "distractor_strength": {"A": 1.5, "B": 1.4, "D": 1.3},
     "subtopic": "ring counter",
     "explanation": "Ring counters feed the last bit back to the first, creating a circular shift pattern useful for sequencing."},
    {"question_id": "T17Q2", "topic": "Flip-flops and registers", "inherent_difficulty": 5.4,
     "question": "A D flip-flop transfers the value at its D input to its output:",
     "option_A": "On the active clock edge.",
     "option_B": "Continuously at all times.",
     "option_C": "Only when power is removed.",
     "option_D": "Randomly within the system.",
     "answer": "A", "distractor_strength": {"B": 2.3, "C": 1.3, "D": 1.4},
     "subtopic": "D flip-flop",
     "explanation": "An edge-triggered D flip-flop samples D and updates Q on the clock edge, ignoring D between edges."},
    {"question_id": "T17Q3", "topic": "Flip-flops and registers", "inherent_difficulty": 6.0,
     "question": "A JK flip-flop with both J = 1 and K = 1 will, on each clock pulse:",
     "option_A": "Toggle (complement) its output.",
     "option_B": "Hold its state within the system.",
     "option_C": "Reset to 0 always under typical loads.",
     "option_D": "Enter an invalid state.",
     "answer": "A", "distractor_strength": {"B": 1.8, "C": 1.9, "D": 2.4},
     "subtopic": "JK toggle",
     "explanation": "JK = 11 makes the flip-flop toggle each clock, unlike the forbidden SR = 11 condition."},
    {"question_id": "T17Q4", "topic": "Flip-flops and registers", "inherent_difficulty": 6.7,
     "question": "A 4-bit shift register is loaded with 1010 and the serial input is held at 0 while it shifts right four times. After four clocks the register holds:",
     "option_A": "1010.",
     "option_B": "0000.",
     "option_C": "0101.",
     "option_D": "1111.",
     "answer": "B", "distractor_strength": {"A": 1.7, "C": 2.3, "D": 1.6},
     "subtopic": "shift register",
     "explanation": "Each right shift brings in a 0 and pushes one bit out; after four shifts all original bits are gone, leaving 0000."},
    {"question_id": "T17Q5", "topic": "Flip-flops and registers", "inherent_difficulty": 7.3,
     "question": "What is the primary purpose of a flip-flop in a digital circuit?",
     "option_A": "To amplify digital signals for most standard configurations.",
     "option_B": "To store a single bit of data and maintain it until changed.",
     "option_C": "To convert analog to digital during normal system operation.",
     "option_D": "To generate clock pulses in typical industrial applications.",
     "answer": "B", "distractor_strength": {"A": 1.4, "C": 1.5, "D": 1.3},
     "subtopic": "flip-flop purpose",
     "explanation": "Flip-flops are bistable memory elements; both output states are stable until clocked or reset."},
    {"question_id": "T17Q6", "topic": "Flip-flops and registers", "inherent_difficulty": 7.9,
     "question": "An SR (set-reset) flip-flop has inputs S = 0 and R = 1. Its output Q will:",
     "option_A": "Become 1 (set).",
     "option_B": "Become 0 (reset).",
     "option_C": "Toggle between 0 and 1.",
     "option_D": "Remain unchanged.",
     "answer": "B", "distractor_strength": {"A": 1.5, "C": 1.4, "D": 1.3},
     "subtopic": "SR logic",
     "explanation": "S=0, R=1 asserts the reset input, forcing Q to 0 and Q' to 1."},
    {"question_id": "T17Q7", "topic": "Flip-flops and registers", "inherent_difficulty": 8.5,
     "question": "A T (toggle) flip-flop with input T = 1 will:",
     "option_A": "Hold its current state in practical implementations.",
     "option_B": "Switch to 1 under standard operating conditions.",
     "option_C": "Complement (toggle) its output on each clock pulse.",
     "option_D": "Switch to 0, depending on specific system requirements.",
     "answer": "C", "distractor_strength": {"A": 1.5, "B": 1.4, "D": 1.3},
     "subtopic": "T flip-flop",
     "explanation": "T = 1 enables toggling; T = 0 holds the state. Used as frequency dividers."},
    {"question_id": "T17Q8", "topic": "Flip-flops and registers", "inherent_difficulty": 9.2,
     "question": "A register is a group of flip-flops used to:",
     "option_A": "Store multiple bits of data, typically aligned for parallel processing.",
     "option_B": "Only measure temperature, depending on specific system requirements.",
     "option_C": "Generate random numbers under standard operating conditions.",
     "option_D": "Eliminate all noise in typical industrial applications and within the system.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.5, "D": 1.3},
     "subtopic": "register",
     "explanation": "An n-bit register stores n bits in parallel; it's the building block of processor storage."},
    {"question_id": "T17Q9", "topic": "Flip-flops and registers", "inherent_difficulty": 9.8,
     "question": "A counter is essentially a register with:",
     "option_A": "Feedback connections between flip-flops to cycle through a sequence of states.",
     "option_B": "No feedback at all, depending on specific system requirements and within the system.",
     "option_C": "Only one flip-flop under standard operating conditions and under typical loads.",
     "option_D": "All flip-flops permanently disabled in typical industrial applications.",
     "answer": "A", "distractor_strength": {"B": 1.4, "C": 1.5, "D": 1.3},
     "subtopic": "counter",
     "explanation": "Counters use feedback; binary counters count 0,1,2,... 2^n-1, then wrap around."}
]
